/* Verify that csrw and csrwi instruction are generated by builtin function.  */

/* { dg-do compile } */
/* { dg-options "-O1" } */
/* { dg-final { scan-assembler-times "\tcsrw\t" 1 } } */
/* { dg-final { scan-assembler-times "\tcsrwi\t" 1 } } */

#include <nds_intrinsic.h>

void
func (unsigned long src)
{
  __nds__csrw (src, 0x304);
}

void
func_i (void)
{
  __nds__csrw (0x4, 0x304);
}
