/* Verify that amoadd.w instruction is generated by builtin function.  */

/* { dg-do compile } */
/* { dg-require-effective-target riscv_atomic } */
/* { dg-final { scan-assembler "\tamoadd.w\t" } } */

#include <nds_intrinsic.h>

void
func (void)
{
  /* We want to perform an atomic add operation.  */
  signed int data, addv, oldv;
  addv = 10;
  /* new value: data + 10  */
  oldv = __nds__amoaddw (addv, &data, UNORDER);
}
