/* Verify that amomaxu.d instruction is generated by builtin function.  */

/* { dg-do compile } */
/* { dg-require-effective-target lp64 } */
/* { dg-require-effective-target riscv_atomic } */
/* { dg-options "-std=gnu99" } */
/* { dg-final { scan-assembler "\tamomaxu.d\t" } } */

#include <nds_intrinsic.h>

void
func (void)
{
  /* We want to perform an atomic unsigned min operation.  */
  unsigned long long data, cmpv, oldv;
  cmpv = 0x22334455;
  /* new value: unsigned maximum (data, cmpv)  */
  oldv = __nds__amomaxud (cmpv, &data, UNORDER);
}
