/* Verify that fsflags and fsflagsi instruction are generated by builtin function.  */

/* { dg-do compile } */
/* { dg-require-effective-target riscv_hard_fp } */
/* { dg-final { scan-assembler-times "\tfsflags\t" 1 } } */
/* { dg-final { scan-assembler-times "\tfsflagsi\t" 1 } } */

#include <nds_intrinsic.h>

void
func (unsigned long src)
{
  unsigned long fflags_data;
  fflags_data = __nds__fsflags (src);
}

void
func_i (void)
{
  unsigned long fflags_data;
  fflags_data = __nds__fsflags (0x0);
}
