/* Verify that csrr instruction is generated by builtin function.  */

/* { dg-do compile } */
/* { dg-final { scan-assembler "\tcsrr\t" } } */

#include <nds_intrinsic.h>

void
func (void)
{
  unsigned long data;
  data = __nds__read_csr (0x304);
}
