/* Verify that ebreak instruction is generated by builtin function.  */

/* { dg-do compile } */
/* { dg-final { scan-assembler-times "\tebreak" 2 } } */

#include <nds_intrinsic.h>

void
func (unsigned long arg)
{
  __nds__ebreak (0x12345678);
  __nds__ebreak (arg);
}
