/* Verify that ecall instruction is generated by builtin function.  */

/* { dg-do compile } */
/* { dg-final { scan-assembler-times "\tecall" 7 } } */

#include <nds_intrinsic.h>

long
func (void)
{
  return __nds__ecall (0x12341234);
}

long
func1 (void)
{
  return __nds__ecall1 (0x12341234, 0x23452345);
}

long
func2 (void)
{
  return __nds__ecall2 (0x12341234, 0x23452345, 0x34563456);
}

long
func3 (void)
{
  return __nds__ecall3 (0x12341234, 0x23452345, 0x34563456, 0x45674567);
}

long
func4 (void)
{
  return __nds__ecall4 (0x12341234, 0x23452345, 0x34563456, 0x45674567,
		       	0x56785678);
}

long
func5 (void)
{
  return __nds__ecall5 (0x12341234, 0x23452345, 0x34563456, 0x45674567,
			0x56785678, 0x67896789);
}

long
func6 (void)
{
  return __nds__ecall6 (0x12341234, 0x23452345, 0x34563456, 0x45674567,
			0x56785678, 0x67896789, 0x789a789a);
}
