/* Verify that frflags instruction is generated by builtin function.  */

/* { dg-do compile } */
/* { dg-final { scan-assembler "\tfrflags" } } */
/* { dg-require-effective-target riscv_hard_fp } */

#include <nds_intrinsic.h>

void
func (void)
{
  unsigned long fflags_data;
  fflags_data = __nds__frflags ();
}
