/* Verify that csrw and csrwi instruction are generated by builtin function.  */

/* { dg-do compile } */
/* { dg-options "-O1" } */
/* { dg-final { scan-assembler-times "\tcsrw\t" 1 } } */
/* { dg-final { scan-assembler-times "\tcsrwi\t" 1 } } */

#include <nds_intrinsic.h>

void
func (void)
{
  unsigned long src = 0x123;
  __nds__csrw (src, 0x456);
}

void
func_i (void)
{
  unsigned long src = 0x123;
  __nds__csrw (src, 0x4);
}
