/* Verify that amoxor.d instruction is generated by builtin function.  */

/* { dg-do compile } */
/* { dg-require-effective-target lp64 } */
/* { dg-require-effective-target riscv_atomic } */
/* { dg-options "-std=gnu99" } */
/* { dg-final { scan-assembler "\tamoxor.d\t" } } */

#include <nds_intrinsic.h>

void
func (void)
{
  /* We want to perform an atomic xor operation.  */
  unsigned long long data, xorv, oldv;
  xorv = 0x22334455;
  /* new value: data xor 0x22334455  */
  oldv = __nds__amoxord (xorv, &data, UNORDER);
}
