/* Verify that fsrm and fsrmi instruction are generated by builtin function.  */

/* { dg-do compile } */
/* { dg-options "-O1" } */
/* { dg-require-effective-target riscv_hard_fp } */
/* { dg-final { scan-assembler-times "\tfsrm\t" 1 } } */
/* { dg-final { scan-assembler-times "\tfsrmi\t" 1 } } */

#include <nds_intrinsic.h>

void
func (void)
{
  unsigned long src;
  src = 0x456;
  __nds__fwrm (src);
}

void
func_i (void)
{
  unsigned long src;
  src = 0x3;
  __nds__fwrm (src);
}
