/* Verify that amoswap.d instruction is generated by builtin function.  */

/* { dg-do compile } */
/* { dg-require-effective-target lp64 } */
/* { dg-require-effective-target riscv_atomic } */
/* { dg-options "-std=gnu99" } */
/* { dg-final { scan-assembler "\tamoswap.d\t" } } */

#include <nds_intrinsic.h>

void
func (void)
{
  /* We want to perform an atomic swap operation.  */
  signed long long data, newv, oldv;
  newv = 10;
  /* new value: 10  */
  oldv = __nds__amoswapd (newv, &data, UNORDER);
}
