/* Verify that amoxor.w instruction is generated by builtin function.  */

/* { dg-do compile } */
/* { dg-require-effective-target riscv_atomic } */
/* { dg-final { scan-assembler "\tamoxor.w\t" } } */

#include <nds_intrinsic.h>

void
func (void)
{
  /* We want to perform an atomic xor operation.  */
  unsigned int data, xorv, oldv;
  xorv = 0x22334455;
  /* new value: data xor 0x22334455  */
  oldv = __nds__amoxorw (xorv, &data, UNORDER);
}
