/* Verify that ebreak instruction is generated by builtin function.  */

/* { dg-do compile } */
/* { dg-final { scan-assembler "\tebreak" } } */

#include <nds_intrinsic.h>

void
func (void)
{
  __nds__ebreak (0x12345678);
}
