/* Verify that csrrc and csrrci instruction are generated by builtin function.  */

/* { dg-do compile } */
/* { dg-options "-O1" } */
/* { dg-final { scan-assembler-times "\tcsrrc\t" 1 } } */
/* { dg-final { scan-assembler-times "\tcsrrci\t" 1 } } */

#include <nds_intrinsic.h>

void
func (void)
{
  unsigned long src, data;
  src = 0x456;
  data = __nds__csrrc (src, 0x123);
}

void
func_i (void)
{
  unsigned long src, data;
  src = 0x456;
  data = __nds__csrrc (src, 0x1);
}
