/* Verify that amoor.w instruction is generated by builtin function.  */

/* { dg-do compile } */
/* { dg-require-effective-target riscv_atomic } */
/* { dg-final { scan-assembler "\tamoor.w\t" } } */

#include <nds_intrinsic.h>

void
func (void)
{
  /* We want to perform an atomic or operation.  */
  unsigned int data, orv, oldv;
  orv = 0x22334455;
  /* new value: data OR 0x22334455  */
  oldv = __nds__amoorw (orv, &data, UNORDER);
}
