/* Verify that amoand.d instruction is generated by builtin function.  */

/* { dg-do compile } */
/* { dg-require-effective-target lp64 } */
/* { dg-require-effective-target riscv_atomic } */
/* { dg-options "-std=gnu99" } */
/* { dg-final { scan-assembler "\tamoand.d\t" } } */

#include <nds_intrinsic.h>

void
func (void)
{
  /* We want to perform an atomic AND operation.  */
  unsigned long long data, andv, oldv;
  andv = 0x22334455;
  /* new value: data AND 0x22334455  */
  oldv = __nds__amoandd (andv, &data, UNORDER);
}
