/* Verify that fscsr instruction is generated by builtin function.  */

/* { dg-do compile } */
/* { dg-final { scan-assembler "\tfscsr\t" } } */
/* { dg-require-effective-target riscv_hard_fp } */

#include <nds_intrinsic.h>

void
func (unsigned long src)
{
  __nds__fscsr (src);
}
