/* Verify that amomin.d instruction is generated by builtin function.  */

/* { dg-do compile } */
/* { dg-require-effective-target lp64 } */
/* { dg-require-effective-target riscv_atomic } */
/* { dg-options "-std=gnu99" } */
/* { dg-final { scan-assembler "\tamomin.d\t" } } */

#include <nds_intrinsic.h>

void
func (void)
{
  /* We want to perform an atomic min operation.  */
  signed long long data, cmpv, oldv;
  cmpv = 10;
  /* new value: minimum (data, cmpv)  */
  oldv = __nds__amomind (cmpv, &data, UNORDER);
}
