/* Verify that amoor.d instruction is generated by builtin function.  */

/* { dg-do compile } */
/* { dg-require-effective-target lp64 } */
/* { dg-require-effective-target riscv_atomic } */
/* { dg-options "-std=gnu99" } */
/* { dg-final { scan-assembler "\tamoor.d\t" } } */

#include <nds_intrinsic.h>

void
func (void)
{
  /* We want to perform an atomic or operation.  */
  unsigned long long data, orv, oldv;
  orv = 0x22334455;
  /* new value: data OR 0x22334455  */
  oldv = __nds__amoord (orv, &data, UNORDER);
}
