/* Verify that frcsr instruction is generated by builtin function.  */

/* { dg-do compile } */
/* { dg-final { scan-assembler "\tfrcsr\t" } } */
/* { dg-require-effective-target riscv_hard_fp } */

#include <nds_intrinsic.h>

void
func (void)
{
  unsigned long fcsr_data;
  fcsr_data = __nds__frcsr ();
}
