/* Verify that amominu.d instruction is generated by builtin function.  */

/* { dg-do compile } */
/* { dg-require-effective-target lp64 } */
/* { dg-require-effective-target riscv_atomic } */
/* { dg-options "-std=gnu99" } */
/* { dg-final { scan-assembler "\tamominu.d\t" } } */

#include <nds_intrinsic.h>

void
func (void)
{
  /* We want to perform an atomic unsigned min operation.  */
  unsigned long long data, cmpv, oldv;
  cmpv = 0x22334455;
  /* new value: unsigned minimum (data, cmpv)  */
  oldv = __nds__amominud (cmpv, &data, UNORDER);
}
