/* Verify that frrm instruction is generated by builtin function.  */

/* { dg-do compile } */
/* { dg-require-effective-target riscv_hard_fp } */
/* { dg-final { scan-assembler "\tfrrm\t" } } */

#include <nds_intrinsic.h>

void
func (void)
{
  unsigned long frm_data;
  frm_data = __nds__frrm ();
}
