/* Verify that lr.w and sc.w instruction are generated by builtin function.  */

/* { dg-do compile } */
/* { dg-require-effective-target riscv_atomic } */
/* { dg-final { scan-assembler "\tlr.w\t" } } */
/* { dg-final { scan-assembler "\tsc.w\t" } } */

#include <nds_intrinsic.h>

void
func (void)
{
  /* We want to perform atomic read-modify-write operations for variable rmw.  */
  unsigned int fail;
  signed int data;
  signed int rmw = 0x0000FFFF; /* The initial value of rmw  */
  fail = 1;
  while (fail)
    {
      data = __nds__lrw (&rmw, UNORDER); /* read  */
      data = data + 1;
      fail = __nds__scw (data, &rmw, UNORDER); /* write  */
    }
}
