/* Verify that ecall instruction is generated by builtin function.  */

/* { dg-do compile } */
/* { dg-final { scan-assembler-times "\tecall" 7 } } */

#include <nds_intrinsic.h>

long
func (void)
{
  return __nds__ecall (0x12341234);
}

long
func1 (long id, long arg1)
{
  return __nds__ecall1 (id, arg1);
}

long
func2 (void)
{
  return __nds__ecall2 (0x12341234, 0x23452345, 0x34563456);
}

long
func3 (long id, long arg1, long arg2, long arg3)
{
  return __nds__ecall3 (id, arg1, arg2, arg3);
}

long
func4 (void)
{
  return __nds__ecall4 (0x12341234, 0x23452345, 0x34563456, 0x45674567,
		       	0x56785678);
}

long
func5 (long id, long arg1, long arg2, long arg3, long arg4, long arg5)
{
  return __nds__ecall5 (id, arg1, arg2, arg3, arg4, arg5);
}

long
func6 (void)
{
  return __nds__ecall6 (0x12341234, 0x23452345, 0x34563456, 0x45674567,
			0x56785678, 0x67896789, 0x789a789a);
}
