/* Verify that amoadd.d instruction is generated by builtin function.  */

/* { dg-do compile } */
/* { dg-require-effective-target lp64 } */
/* { dg-require-effective-target riscv_atomic } */
/* { dg-options "-std=gnu99" } */
/* { dg-final { scan-assembler "\tamoadd.d\t" } } */

#include <nds_intrinsic.h>

void
func (void)
{
  /* We want to perform an atomic add operation.  */
  signed long long data, addv, oldv;
  addv = 10;
  /* new value: data + 10  */
  oldv = __nds__amoaddd (addv, &data, UNORDER);
}
