/* Verify that csrc and csrci instruction are generated by builtin function.  */

/* { dg-do compile } */
/* { dg-final { scan-assembler-times "\tcsrc\t" 1 } } */
/* { dg-final { scan-assembler-times "\tcsrci\t" 1 } } */

#include <nds_intrinsic.h>

void
func (unsigned long src)
{
  __nds__csrc (src, 0x456);
}

void
func_i (void)
{
  __nds__csrc (0x4, 0x304);
}
