/* Verify that fsflags and fsflagsi instruction are generated by builtin function.  */

/* { dg-do compile } */
/* { dg-options "-O1" } */
/* { dg-require-effective-target riscv_hard_fp } */
/* { dg-final { scan-assembler-times "\tfsflags\t" 1 } } */
/* { dg-final { scan-assembler-times "\tfsflagsi\t" 1 } } */

#include <nds_intrinsic.h>

void
func (void)
{
  unsigned long src;
  src = 0x168;
  __nds__fsflags (src);
}

void
func_i (void)
{
  unsigned long src;
  src = 0x0;
  __nds__fsflags (src);
}
