/* Verify that amoand.w instruction is generated by builtin function.  */

/* { dg-do compile } */
/* { dg-require-effective-target riscv_atomic } */
/* { dg-final { scan-assembler "\tamoand.w\t" } } */

#include <nds_intrinsic.h>

void
func (void)
{
  /* We want to perform an atomic AND operation.  */
  unsigned int data, andv, oldv;
  andv = 0x22334455;
  /* new value: data AND 0x22334455  */
  oldv = __nds__amoandw (andv, &data, UNORDER);
}
