/* Verify that amominu.w instruction is generated by builtin function.  */

/* { dg-do compile } */
/* { dg-require-effective-target riscv_atomic } */
/* { dg-final { scan-assembler "\tamominu.w\t" } } */

#include <nds_intrinsic.h>

void
func (void)
{
  /* We want to perform an atomic unsigned min operation.  */
  unsigned int data, cmpv, oldv;
  cmpv = 0x22334455;
  /* new value: unsigned minimum (data, cmpv)  */
  oldv = __nds__amominuw (cmpv, &data, UNORDER);
}
