/* Verify that fsrm and fsrmi instruction are generated by builtin function.  */

/* { dg-do compile } */
/* { dg-require-effective-target riscv_hard_fp } */
/* { dg-final { scan-assembler-times "\tfsrm\t" 1 } } */
/* { dg-final { scan-assembler-times "\tfsrmi\t" 1 } } */

#include <nds_intrinsic.h>

void
func (unsigned long src)
{
  __nds__fwrm (src);
}

void
func_i (void)
{
  __nds__fwrm (0x3);
}
