/* Verify that csrs and csrsi instruction are generated by builtin function.  */

/* { dg-do compile } */
/* { dg-final { scan-assembler-times "\tcsrs\t" 1 } } */
/* { dg-final { scan-assembler-times "\tcsrsi\t" 1 } } */

#include <nds_intrinsic.h>

void
func (unsigned long src)
{
  __nds__csrs (src, 0x304);
}

void
func_i (void)
{
  __nds__csrs (0x4, 0x304);
}
