/* Verify that fence and fence.i instruction are generated by builtin function.  */

/* { dg-do compile } */
/* { dg-final { scan-assembler-times "\tfence\tw,\\s*w" 1 } } */
/* { dg-final { scan-assembler-times "\tfence.i" 1 } } */

#include <nds_intrinsic.h>

void
func (void)
{
  __nds__fence (FENCE_W, FENCE_W);
}

void
func_i (void)
{
  __nds__fencei ();
}
