#ifndef NDS32_OPTS_H
#define NDS32_OPTS_H 
#define NDS32_DEFAULT_CACHE_BLOCK_SIZE 16
#define NDS32_DEFAULT_ISR_VECTOR_SIZE TARGET_DEFAULT_ISR_VECTOR_SIZE
enum nds32_arch_type
{
  ARCH_V2,
  ARCH_V2J,
  ARCH_V3,
  ARCH_V3J,
  ARCH_V3M,
  ARCH_V3M_PLUS,
  ARCH_V3F,
  ARCH_V3S
};
enum nds32_cpu_type
{
  CPU_N6,
  CPU_N7,
  CPU_N8,
  CPU_E8,
  CPU_N9,
  CPU_N10,
  CPU_GRAYWOLF,
  CPU_N12,
  CPU_N13,
  CPU_PANTHER,
  CPU_SIMPLE
};
enum nds32_memory_model_type
{
  MEMORY_MODEL_SLOW,
  MEMORY_MODEL_FAST
};
enum nds32_cmodel_type
{
  CMODEL_SMALL,
  CMODEL_MEDIUM,
  CMODEL_LARGE
};
enum nds32_ict_model_type
{
  ICT_MODEL_SMALL,
  ICT_MODEL_LARGE
};
enum nds32_mul_type
{
  MUL_TYPE_FAST_1,
  MUL_TYPE_FAST_2,
  MUL_TYPE_SLOW
};
enum nds32_register_ports
{
  REG_PORT_3R2W,
  REG_PORT_2R1W
};
enum abi_type
{
  NDS32_ABI_V2,
  NDS32_ABI_V2_FP_PLUS
};
enum float_reg_number
{
  NDS32_CONFIG_FPU_0,
  NDS32_CONFIG_FPU_1,
  NDS32_CONFIG_FPU_2,
  NDS32_CONFIG_FPU_3,
  NDS32_CONFIG_FPU_4,
  NDS32_CONFIG_FPU_5,
  NDS32_CONFIG_FPU_6,
  NDS32_CONFIG_FPU_7
};
#endif
