#ifndef _NDS_INTRINSIC_H
#define _NDS_INTRINSIC_H

enum riscv_csrs
{
  NDS_FFLAGS = 4096,
  NDS_FRM,
  NDS_FCSR,
  NDS_CYCLE,
  NDS_TIME,
  NDS_INSTRET,
  NDS_HPMCOUNTER3,
  NDS_HPMCOUNTER4,
  NDS_HPMCOUNTER5,
  NDS_HPMCOUNTER6,
  NDS_HPMCOUNTER7,
  NDS_HPMCOUNTER8,
  NDS_HPMCOUNTER9,
  NDS_HPMCOUNTER10,
  NDS_HPMCOUNTER11,
  NDS_HPMCOUNTER12,
  NDS_HPMCOUNTER13,
  NDS_HPMCOUNTER14,
  NDS_HPMCOUNTER15,
  NDS_HPMCOUNTER16,
  NDS_HPMCOUNTER17,
  NDS_HPMCOUNTER18,
  NDS_HPMCOUNTER19,
  NDS_HPMCOUNTER20,
  NDS_HPMCOUNTER21,
  NDS_HPMCOUNTER22,
  NDS_HPMCOUNTER23,
  NDS_HPMCOUNTER24,
  NDS_HPMCOUNTER25,
  NDS_HPMCOUNTER26,
  NDS_HPMCOUNTER27,
  NDS_HPMCOUNTER28,
  NDS_HPMCOUNTER29,
  NDS_HPMCOUNTER30,
  NDS_HPMCOUNTER31,
  NDS_SSTATUS,
  NDS_SIE,
  NDS_STVEC,
  NDS_SSCRATCH,
  NDS_SEPC,
  NDS_SCAUSE,
  NDS_SBADADDR,
  NDS_SIP,
  NDS_SPTBR,
  NDS_MSTATUS,
  NDS_MISA,
  NDS_MEDELEG,
  NDS_MIDELEG,
  NDS_MIE,
  NDS_MTVEC,
  NDS_MSCRATCH,
  NDS_MEPC,
  NDS_MCAUSE,
  NDS_MBADADDR,
  NDS_MIP,
  NDS_TSELECT,
  NDS_TDATA1,
  NDS_TDATA2,
  NDS_TDATA3,
  NDS_DCSR,
  NDS_DPC,
  NDS_DSCRATCH,
  NDS_MCYCLE,
  NDS_MINSTRET,
  NDS_MHPMCOUNTER3,
  NDS_MHPMCOUNTER4,
  NDS_MHPMCOUNTER5,
  NDS_MHPMCOUNTER6,
  NDS_MHPMCOUNTER7,
  NDS_MHPMCOUNTER8,
  NDS_MHPMCOUNTER9,
  NDS_MHPMCOUNTER10,
  NDS_MHPMCOUNTER11,
  NDS_MHPMCOUNTER12,
  NDS_MHPMCOUNTER13,
  NDS_MHPMCOUNTER14,
  NDS_MHPMCOUNTER15,
  NDS_MHPMCOUNTER16,
  NDS_MHPMCOUNTER17,
  NDS_MHPMCOUNTER18,
  NDS_MHPMCOUNTER19,
  NDS_MHPMCOUNTER20,
  NDS_MHPMCOUNTER21,
  NDS_MHPMCOUNTER22,
  NDS_MHPMCOUNTER23,
  NDS_MHPMCOUNTER24,
  NDS_MHPMCOUNTER25,
  NDS_MHPMCOUNTER26,
  NDS_MHPMCOUNTER27,
  NDS_MHPMCOUNTER28,
  NDS_MHPMCOUNTER29,
  NDS_MHPMCOUNTER30,
  NDS_MHPMCOUNTER31,
  NDS_MUCOUNTEREN,
  NDS_MSCOUNTEREN,
  NDS_MHPMEVENT3,
  NDS_MHPMEVENT4,
  NDS_MHPMEVENT5,
  NDS_MHPMEVENT6,
  NDS_MHPMEVENT7,
  NDS_MHPMEVENT8,
  NDS_MHPMEVENT9,
  NDS_MHPMEVENT10,
  NDS_MHPMEVENT11,
  NDS_MHPMEVENT12,
  NDS_MHPMEVENT13,
  NDS_MHPMEVENT14,
  NDS_MHPMEVENT15,
  NDS_MHPMEVENT16,
  NDS_MHPMEVENT17,
  NDS_MHPMEVENT18,
  NDS_MHPMEVENT19,
  NDS_MHPMEVENT20,
  NDS_MHPMEVENT21,
  NDS_MHPMEVENT22,
  NDS_MHPMEVENT23,
  NDS_MHPMEVENT24,
  NDS_MHPMEVENT25,
  NDS_MHPMEVENT26,
  NDS_MHPMEVENT27,
  NDS_MHPMEVENT28,
  NDS_MHPMEVENT29,
  NDS_MHPMEVENT30,
  NDS_MHPMEVENT31,
  NDS_MVENDORID,
  NDS_MARCHID,
  NDS_MIMPID,
  NDS_MHARTID,
  NDS_CYCLEH,
  NDS_TIMEH,
  NDS_INSTRETH,
  NDS_HPMCOUNTER3H,
  NDS_HPMCOUNTER4H,
  NDS_HPMCOUNTER5H,
  NDS_HPMCOUNTER6H,
  NDS_HPMCOUNTER7H,
  NDS_HPMCOUNTER8H,
  NDS_HPMCOUNTER9H,
  NDS_HPMCOUNTER10H,
  NDS_HPMCOUNTER11H,
  NDS_HPMCOUNTER12H,
  NDS_HPMCOUNTER13H,
  NDS_HPMCOUNTER14H,
  NDS_HPMCOUNTER15H,
  NDS_HPMCOUNTER16H,
  NDS_HPMCOUNTER17H,
  NDS_HPMCOUNTER18H,
  NDS_HPMCOUNTER19H,
  NDS_HPMCOUNTER20H,
  NDS_HPMCOUNTER21H,
  NDS_HPMCOUNTER22H,
  NDS_HPMCOUNTER23H,
  NDS_HPMCOUNTER24H,
  NDS_HPMCOUNTER25H,
  NDS_HPMCOUNTER26H,
  NDS_HPMCOUNTER27H,
  NDS_HPMCOUNTER28H,
  NDS_HPMCOUNTER29H,
  NDS_HPMCOUNTER30H,
  NDS_HPMCOUNTER31H,
  NDS_MCYCLEH,
  NDS_MINSTRETH,
  NDS_MHPMCOUNTER3H,
  NDS_MHPMCOUNTER4H,
  NDS_MHPMCOUNTER5H,
  NDS_MHPMCOUNTER6H,
  NDS_MHPMCOUNTER7H,
  NDS_MHPMCOUNTER8H,
  NDS_MHPMCOUNTER9H,
  NDS_MHPMCOUNTER10H,
  NDS_MHPMCOUNTER11H,
  NDS_MHPMCOUNTER12H,
  NDS_MHPMCOUNTER13H,
  NDS_MHPMCOUNTER14H,
  NDS_MHPMCOUNTER15H,
  NDS_MHPMCOUNTER16H,
  NDS_MHPMCOUNTER17H,
  NDS_MHPMCOUNTER18H,
  NDS_MHPMCOUNTER19H,
  NDS_MHPMCOUNTER20H,
  NDS_MHPMCOUNTER21H,
  NDS_MHPMCOUNTER22H,
  NDS_MHPMCOUNTER23H,
  NDS_MHPMCOUNTER24H,
  NDS_MHPMCOUNTER25H,
  NDS_MHPMCOUNTER26H,
  NDS_MHPMCOUNTER27H,
  NDS_MHPMCOUNTER28H,
  NDS_MHPMCOUNTER29H,
  NDS_MHPMCOUNTER30H,
  NDS_MHPMCOUNTER31H,
  NDS_MICM_CFG,
  NDS_MDCM_CFG,
  NDS_MMSC_CFG
};

#define __nds__msync_all() asm volatile ("fence" : : : "memory")

#define __nds__cctl_l1d_wball_one_lvl()
#define __nds__cctl_l1d_wball_alvl()
#define __nds__cctl_l1d_invalall()

#define __nds__mfsr(srname) \
  (__builtin_riscv_csrr ((srname)))
#define __nds__mtsr(val, srname) \
  (__builtin_riscv_csrw ((val), (srname)))

#define __nds__ecall(sysid) \
  (__builtin_riscv_ecall ((sysid)))
#define __nds__ecall1(sysid, a) \
  (__builtin_riscv_csrw ((sysid), (a)))
#define __nds__ecall2(sysid, a, b) \
  (__builtin_riscv_csrw ((sysid), (a), (b)))
#define __nds__ecall3(sysid, a, b, c) \
  (__builtin_riscv_csrw ((sysid), (a), (b), (c)))
#define __nds__ecall1(sysid, a, b, c, d) \
  (__builtin_riscv_csrw ((sysid), (a), (b), (c), (d)))
#define __nds__ecall1(sysid, a, b, c, d, e) \
  (__builtin_riscv_csrw ((sysid), (a), (b), (c), (d), (e)))
#define __nds__ecall1(sysid, a, b, c, d, e, f) \
  (__builtin_riscv_csrw ((sysid), (a), (b), (c), (d), (e), (f)))

static unsigned int __nds__rotr(unsigned int val, unsigned int ror) __attribute__((unused));
static unsigned int __nds__wsbh(unsigned int a) __attribute__((unused));

static unsigned int __nds__rotr(unsigned int val, unsigned int ror)
{
  unsigned int rotr = ror & 0x1f;
  return (val >> rotr) | (val << (sizeof(val)*8 - rotr));
}

static unsigned int __nds__wsbh(unsigned int a)
{
  unsigned int b0 = (a >>  0) & 0xff;
  unsigned int b1 = (a >>  8) & 0xff;
  unsigned int b2 = (a >> 16) & 0xff;
  unsigned int b3 = (a >> 24) & 0xff;
  return (b0 << 8) | (b1 << 0) | (b2 << 24) | (b3 << 16);
}

#endif
