/* Subroutines used for expanding RISC-V builtins.
   Copyright (C) 2011-2020 Free Software Foundation, Inc.
   Contributed by Andrew Waterman (andrew@sifive.com).

This file is part of GCC.

GCC is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 3, or (at your option)
any later version.

GCC is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with GCC; see the file COPYING3.  If not see
<http://www.gnu.org/licenses/>.  */

#define IN_TARGET_CODE 1

#include "config.h"
#include "system.h"
#include "coretypes.h"
#include "tm.h"
#include "rtl.h"
#include "tree.h"
#include "gimple-expr.h"
#include "memmodel.h"
#include "expmed.h"
#include "profile-count.h"
#include "optabs.h"
#include "recog.h"
#include "diagnostic-core.h"
#include "stor-layout.h"
#include "function.h"
#include "emit-rtl.h"
#include "expr.h"
#include "explow.h"
#include "langhooks.h"

/* Macros to create an enumeration identifier for a function prototype.  */
#define RISCV_FTYPE_NAME0(A) RISCV_##A##_FTYPE
#define RISCV_FTYPE_NAME1(A, B) RISCV_##A##_FTYPE_##B
#define RISCV_FTYPE_NAME2(A, B, C) RISCV_##A##_FTYPE_##B##_##C
#define RISCV_FTYPE_NAME3(A, B, C, D) \
  RISCV_##A##_FTYPE_##B##_##C##_##D
#define RISCV_FTYPE_NAME4(A, B, C, D, E) \
  RISCV_##A##_FTYPE_##B##_##C##_##D##_##E
#define RISCV_FTYPE_NAME5(A, B, C, D, E, F) \
  RISCV_##A##_FTYPE_##B##_##C##_##D##_##E##_##F
#define RISCV_FTYPE_NAME6(A, B, C, D, E, F, G) \
  RISCV_##A##_FTYPE_##B##_##C##_##D##_##E##_##F##_##G
#define RISCV_FTYPE_NAME7(A, B, C, D, E, F, G, H) \
  RISCV_##A##_FTYPE_##B##_##C##_##D##_##E##_##F##_##G##_##H

/* Classifies the prototype of a built-in function.  */
enum riscv_function_type {
#define DEF_RISCV_FTYPE(NARGS, LIST) RISCV_FTYPE_NAME##NARGS LIST,
#include "config/riscv/riscv-ftypes.def"
#undef DEF_RISCV_FTYPE
  RISCV_MAX_FTYPE_MAX
};

/* Specifies how a built-in function should be converted into rtl.  */
enum riscv_builtin_type {
  /* The function corresponds directly to an .md pattern.  */
  RISCV_BUILTIN_DIRECT,

  /* Likewise, but with return type VOID.  */
  RISCV_BUILTIN_DIRECT_NO_TARGET
};

enum riscv_builtins
{
  RISCV_BUILTIN_FRFLAGS_FENV,
  RISCV_BUILTIN_FSFLAGS_FENV,
  RISCV_BUILTIN_CSRR,
  RISCV_BUILTIN_CSRW,
  RISCV_BUILTIN_GET_SP,
  RISCV_BUILTIN_SET_SP,
  RISCV_BUILTIN_ECALL,
  RISCV_BUILTIN_FENCE,
  RISCV_BUILTIN_FENCEI,
  RISCV_BUILTIN_FRCSR,
  RISCV_BUILTIN_FSCSR,
  RISCV_BUILTIN_FWCSR,
  RISCV_BUILTIN_FRRM,
  RISCV_BUILTIN_FSRM,
  RISCV_BUILTIN_FWRM,
  RISCV_BUILTIN_FRFLAGS,
  RISCV_BUILTIN_FSFLAGS,
  RISCV_BUILTIN_FWFLAGS,
  RISCV_BUILTIN_LRW,
  RISCV_BUILTIN_LRD,
  RISCV_BUILTIN_SCW,
  RISCV_BUILTIN_SCD,
  RISCV_BUILTIN_AMOW,
  RISCV_BUILTIN_AMOD,
  RISCV_BUILTIN_EBREAK,
  RISCV_BUILTIN_CSRRW,
  RISCV_BUILTIN_CSRRS,
  RISCV_BUILTIN_CSRRC,
  RISCV_BUILTIN_CSRS,
  RISCV_BUILTIN_CSRC,
  RISCV_BUILTIN_DSP_BEGIN,
  RISCV_BUILTIN_ADD16,
  RISCV_BUILTIN_V_UADD16,
  RISCV_BUILTIN_V_SADD16,
  RISCV_BUILTIN_RADD16,
  RISCV_BUILTIN_V_RADD16,
  RISCV_BUILTIN_URADD16,
  RISCV_BUILTIN_V_URADD16,
  RISCV_BUILTIN_KADD16,
  RISCV_BUILTIN_V_KADD16,
  RISCV_BUILTIN_UKADD16,
  RISCV_BUILTIN_V_UKADD16,
  RISCV_BUILTIN_SUB16,
  RISCV_BUILTIN_V_USUB16,
  RISCV_BUILTIN_V_SSUB16,
  RISCV_BUILTIN_RSUB16,
  RISCV_BUILTIN_V_RSUB16,
  RISCV_BUILTIN_URSUB16,
  RISCV_BUILTIN_V_URSUB16,
  RISCV_BUILTIN_KSUB16,
  RISCV_BUILTIN_V_KSUB16,
  RISCV_BUILTIN_UKSUB16,
  RISCV_BUILTIN_V_UKSUB16,
  RISCV_BUILTIN_CRAS16,
  RISCV_BUILTIN_V_UCRAS16,
  RISCV_BUILTIN_V_SCRAS16,
  RISCV_BUILTIN_RCRAS16,
  RISCV_BUILTIN_V_RCRAS16,
  RISCV_BUILTIN_URCRAS16,
  RISCV_BUILTIN_V_URCRAS16,
  RISCV_BUILTIN_KCRAS16,
  RISCV_BUILTIN_V_KCRAS16,
  RISCV_BUILTIN_UKCRAS16,
  RISCV_BUILTIN_V_UKCRAS16,
  RISCV_BUILTIN_CRSA16,
  RISCV_BUILTIN_V_UCRSA16,
  RISCV_BUILTIN_V_SCRSA16,
  RISCV_BUILTIN_RCRSA16,
  RISCV_BUILTIN_V_RCRSA16,
  RISCV_BUILTIN_URCRSA16,
  RISCV_BUILTIN_V_URCRSA16,
  RISCV_BUILTIN_KCRSA16,
  RISCV_BUILTIN_V_KCRSA16,
  RISCV_BUILTIN_UKCRSA16,
  RISCV_BUILTIN_V_UKCRSA16,
  RISCV_BUILTIN_ADD8,
  RISCV_BUILTIN_V_UADD8,
  RISCV_BUILTIN_V_SADD8,
  RISCV_BUILTIN_RADD8,
  RISCV_BUILTIN_V_RADD8,
  RISCV_BUILTIN_URADD8,
  RISCV_BUILTIN_V_URADD8,
  RISCV_BUILTIN_KADD8,
  RISCV_BUILTIN_V_KADD8,
  RISCV_BUILTIN_UKADD8,
  RISCV_BUILTIN_V_UKADD8,
  RISCV_BUILTIN_SUB8,
  RISCV_BUILTIN_V_USUB8,
  RISCV_BUILTIN_V_SSUB8,
  RISCV_BUILTIN_RSUB8,
  RISCV_BUILTIN_V_RSUB8,
  RISCV_BUILTIN_URSUB8,
  RISCV_BUILTIN_V_URSUB8,
  RISCV_BUILTIN_KSUB8,
  RISCV_BUILTIN_V_KSUB8,
  RISCV_BUILTIN_UKSUB8,
  RISCV_BUILTIN_V_UKSUB8,
  RISCV_BUILTIN_SRA16,
  RISCV_BUILTIN_V_SRA16,
  RISCV_BUILTIN_SRA16_U,
  RISCV_BUILTIN_V_SRA16_U,
  RISCV_BUILTIN_SRL16,
  RISCV_BUILTIN_V_SRL16,
  RISCV_BUILTIN_SRL16_U,
  RISCV_BUILTIN_V_SRL16_U,
  RISCV_BUILTIN_SLL16,
  RISCV_BUILTIN_V_SLL16,
  RISCV_BUILTIN_KSLL16,
  RISCV_BUILTIN_V_KSLL16,
  RISCV_BUILTIN_KSLRA16,
  RISCV_BUILTIN_V_KSLRA16,
  RISCV_BUILTIN_KSLRA16_U,
  RISCV_BUILTIN_V_KSLRA16_U,
  RISCV_BUILTIN_CMPEQ16,
  RISCV_BUILTIN_V_SCMPEQ16,
  RISCV_BUILTIN_V_UCMPEQ16,
  RISCV_BUILTIN_SCMPLT16,
  RISCV_BUILTIN_V_SCMPLT16,
  RISCV_BUILTIN_SCMPLE16,
  RISCV_BUILTIN_V_SCMPLE16,
  RISCV_BUILTIN_UCMPLT16,
  RISCV_BUILTIN_V_UCMPLT16,
  RISCV_BUILTIN_UCMPLE16,
  RISCV_BUILTIN_V_UCMPLE16,
  RISCV_BUILTIN_CMPEQ8,
  RISCV_BUILTIN_V_SCMPEQ8,
  RISCV_BUILTIN_V_UCMPEQ8,
  RISCV_BUILTIN_SCMPLT8,
  RISCV_BUILTIN_V_SCMPLT8,
  RISCV_BUILTIN_SCMPLE8,
  RISCV_BUILTIN_V_SCMPLE8,
  RISCV_BUILTIN_UCMPLT8,
  RISCV_BUILTIN_V_UCMPLT8,
  RISCV_BUILTIN_UCMPLE8,
  RISCV_BUILTIN_V_UCMPLE8,
  RISCV_BUILTIN_SMIN16,
  RISCV_BUILTIN_V_SMIN16,
  RISCV_BUILTIN_UMIN16,
  RISCV_BUILTIN_V_UMIN16,
  RISCV_BUILTIN_SMAX16,
  RISCV_BUILTIN_V_SMAX16,
  RISCV_BUILTIN_UMAX16,
  RISCV_BUILTIN_V_UMAX16,
  RISCV_BUILTIN_SCLIP16,
  RISCV_BUILTIN_V_SCLIP16,
  RISCV_BUILTIN_UCLIP16,
  RISCV_BUILTIN_V_UCLIP16,
  RISCV_BUILTIN_KHM16,
  RISCV_BUILTIN_V_KHM16,
  RISCV_BUILTIN_KHMX16,
  RISCV_BUILTIN_V_KHMX16,
  RISCV_BUILTIN_KHM8,
  RISCV_BUILTIN_V_KHM8,
  RISCV_BUILTIN_KHMX8,
  RISCV_BUILTIN_V_KHMX8,
  RISCV_BUILTIN_KABS16,
  RISCV_BUILTIN_V_KABS16,
  RISCV_BUILTIN_SMUL16,
  RISCV_BUILTIN_V_SMUL16,
  RISCV_BUILTIN_SMULX16,
  RISCV_BUILTIN_V_SMULX16,
  RISCV_BUILTIN_UMUL16,
  RISCV_BUILTIN_V_UMUL16,
  RISCV_BUILTIN_UMULX16,
  RISCV_BUILTIN_V_UMULX16,
  RISCV_BUILTIN_SMUL8,
  RISCV_BUILTIN_V_SMUL8,
  RISCV_BUILTIN_SMULX8,
  RISCV_BUILTIN_V_SMULX8,
  RISCV_BUILTIN_UMUL8,
  RISCV_BUILTIN_V_UMUL8,
  RISCV_BUILTIN_UMULX8,
  RISCV_BUILTIN_V_UMULX8,
  RISCV_BUILTIN_SMIN8,
  RISCV_BUILTIN_V_SMIN8,
  RISCV_BUILTIN_UMIN8,
  RISCV_BUILTIN_V_UMIN8,
  RISCV_BUILTIN_SMAX8,
  RISCV_BUILTIN_V_SMAX8,
  RISCV_BUILTIN_UMAX8,
  RISCV_BUILTIN_V_UMAX8,
  RISCV_BUILTIN_KABS8,
  RISCV_BUILTIN_V_KABS8,
  RISCV_BUILTIN_SUNPKD810,
  RISCV_BUILTIN_V_SUNPKD810,
  RISCV_BUILTIN_SUNPKD820,
  RISCV_BUILTIN_V_SUNPKD820,
  RISCV_BUILTIN_SUNPKD830,
  RISCV_BUILTIN_V_SUNPKD830,
  RISCV_BUILTIN_SUNPKD831,
  RISCV_BUILTIN_V_SUNPKD831,
  RISCV_BUILTIN_SUNPKD832,
  RISCV_BUILTIN_V_SUNPKD832,
  RISCV_BUILTIN_ZUNPKD810,
  RISCV_BUILTIN_V_ZUNPKD810,
  RISCV_BUILTIN_ZUNPKD820,
  RISCV_BUILTIN_V_ZUNPKD820,
  RISCV_BUILTIN_ZUNPKD830,
  RISCV_BUILTIN_V_ZUNPKD830,
  RISCV_BUILTIN_ZUNPKD831,
  RISCV_BUILTIN_V_ZUNPKD831,
  RISCV_BUILTIN_ZUNPKD832,
  RISCV_BUILTIN_V_ZUNPKD832,
  RISCV_BUILTIN_RADDW,
  RISCV_BUILTIN_URADDW,
  RISCV_BUILTIN_RSUBW,
  RISCV_BUILTIN_URSUBW,
  RISCV_BUILTIN_SRA_U,
  RISCV_BUILTIN_KSLL,
  RISCV_BUILTIN_PKBB16,
  RISCV_BUILTIN_V_PKBB16,
  RISCV_BUILTIN_PKBT16,
  RISCV_BUILTIN_V_PKBT16,
  RISCV_BUILTIN_PKTB16,
  RISCV_BUILTIN_V_PKTB16,
  RISCV_BUILTIN_PKTT16,
  RISCV_BUILTIN_V_PKTT16,
  RISCV_BUILTIN_SMMUL,
  RISCV_BUILTIN_SMMUL_U,
  RISCV_BUILTIN_KMMAC,
  RISCV_BUILTIN_KMMAC_U,
  RISCV_BUILTIN_KMMSB,
  RISCV_BUILTIN_KMMSB_U,
  RISCV_BUILTIN_KWMMUL,
  RISCV_BUILTIN_KWMMUL_U,
  RISCV_BUILTIN_SMMWB,
  RISCV_BUILTIN_V_SMMWB,
  RISCV_BUILTIN_SMMWB_U,
  RISCV_BUILTIN_V_SMMWB_U,
  RISCV_BUILTIN_SMMWT,
  RISCV_BUILTIN_V_SMMWT,
  RISCV_BUILTIN_SMMWT_U,
  RISCV_BUILTIN_V_SMMWT_U,
  RISCV_BUILTIN_KMMAWB,
  RISCV_BUILTIN_V_KMMAWB,
  RISCV_BUILTIN_KMMAWB_U,
  RISCV_BUILTIN_V_KMMAWB_U,
  RISCV_BUILTIN_KMMAWT,
  RISCV_BUILTIN_V_KMMAWT,
  RISCV_BUILTIN_KMMAWT_U,
  RISCV_BUILTIN_V_KMMAWT_U,
  RISCV_BUILTIN_SMBB,
  RISCV_BUILTIN_V_SMBB,
  RISCV_BUILTIN_SMBT,
  RISCV_BUILTIN_V_SMBT,
  RISCV_BUILTIN_SMTT,
  RISCV_BUILTIN_V_SMTT,
  RISCV_BUILTIN_KMDA,
  RISCV_BUILTIN_V_KMDA,
  RISCV_BUILTIN_KMXDA,
  RISCV_BUILTIN_V_KMXDA,
  RISCV_BUILTIN_SMDS,
  RISCV_BUILTIN_V_SMDS,
  RISCV_BUILTIN_SMDRS,
  RISCV_BUILTIN_V_SMDRS,
  RISCV_BUILTIN_SMXDS,
  RISCV_BUILTIN_V_SMXDS,
  RISCV_BUILTIN_KMABB,
  RISCV_BUILTIN_V_KMABB,
  RISCV_BUILTIN_KMABT,
  RISCV_BUILTIN_V_KMABT,
  RISCV_BUILTIN_KMATT,
  RISCV_BUILTIN_V_KMATT,
  RISCV_BUILTIN_KMADA,
  RISCV_BUILTIN_V_KMADA,
  RISCV_BUILTIN_KMAXDA,
  RISCV_BUILTIN_V_KMAXDA,
  RISCV_BUILTIN_KMADS,
  RISCV_BUILTIN_V_KMADS,
  RISCV_BUILTIN_KMADRS,
  RISCV_BUILTIN_V_KMADRS,
  RISCV_BUILTIN_KMAXDS,
  RISCV_BUILTIN_V_KMAXDS,
  RISCV_BUILTIN_KMSDA,
  RISCV_BUILTIN_V_KMSDA,
  RISCV_BUILTIN_KMSXDA,
  RISCV_BUILTIN_V_KMSXDA,
  RISCV_BUILTIN_SMAL,
  RISCV_BUILTIN_V_SMAL,
  RISCV_BUILTIN_BITREV,
  RISCV_BUILTIN_WEXT,
  RISCV_BUILTIN_BPICK,
  RISCV_BUILTIN_INSB,
  RISCV_BUILTIN_SADD64,
  RISCV_BUILTIN_UADD64,
  RISCV_BUILTIN_RADD64,
  RISCV_BUILTIN_URADD64,
  RISCV_BUILTIN_KADD64,
  RISCV_BUILTIN_UKADD64,
  RISCV_BUILTIN_SSUB64,
  RISCV_BUILTIN_USUB64,
  RISCV_BUILTIN_RSUB64,
  RISCV_BUILTIN_URSUB64,
  RISCV_BUILTIN_KSUB64,
  RISCV_BUILTIN_UKSUB64,
  RISCV_BUILTIN_SMAR64,
  RISCV_BUILTIN_SMSR64,
  RISCV_BUILTIN_UMAR64,
  RISCV_BUILTIN_UMSR64,
  RISCV_BUILTIN_KMAR64,
  RISCV_BUILTIN_KMSR64,
  RISCV_BUILTIN_UKMAR64,
  RISCV_BUILTIN_UKMSR64,
  RISCV_BUILTIN_SMALBB,
  RISCV_BUILTIN_V_SMALBB,
  RISCV_BUILTIN_SMALBT,
  RISCV_BUILTIN_V_SMALBT,
  RISCV_BUILTIN_SMALTT,
  RISCV_BUILTIN_V_SMALTT,
  RISCV_BUILTIN_SMALDA,
  RISCV_BUILTIN_V_SMALDA,
  RISCV_BUILTIN_SMALXDA,
  RISCV_BUILTIN_V_SMALXDA,
  RISCV_BUILTIN_SMALDS,
  RISCV_BUILTIN_V_SMALDS,
  RISCV_BUILTIN_SMALDRS,
  RISCV_BUILTIN_V_SMALDRS,
  RISCV_BUILTIN_SMALXDS,
  RISCV_BUILTIN_V_SMALXDS,
  RISCV_BUILTIN_SMSLDA,
  RISCV_BUILTIN_V_SMSLDA,
  RISCV_BUILTIN_SMSLXDA,
  RISCV_BUILTIN_V_SMSLXDA,
  RISCV_BUILTIN_UCLIP32,
  RISCV_BUILTIN_SCLIP32,
  RISCV_BUILTIN_KABS,
  RISCV_BUILTIN_KADDW,
  RISCV_BUILTIN_KADDH,
  RISCV_BUILTIN_KSUBW,
  RISCV_BUILTIN_KSUBH,
  RISCV_BUILTIN_UKADDW,
  RISCV_BUILTIN_UKADDH,
  RISCV_BUILTIN_UKSUBW,
  RISCV_BUILTIN_UKSUBH,
  RISCV_BUILTIN_KSLRAW,
  RISCV_BUILTIN_KSLRAW_U,
  RISCV_BUILTIN_KDMBB,
  RISCV_BUILTIN_V_KDMBB,
  RISCV_BUILTIN_KDMBT,
  RISCV_BUILTIN_V_KDMBT,
  RISCV_BUILTIN_KDMTT,
  RISCV_BUILTIN_V_KDMTT,
  RISCV_BUILTIN_KHMBB,
  RISCV_BUILTIN_V_KHMBB,
  RISCV_BUILTIN_KHMBT,
  RISCV_BUILTIN_V_KHMBT,
  RISCV_BUILTIN_KHMTT,
  RISCV_BUILTIN_V_KHMTT,
  RISCV_BUILTIN_AVE,
  RISCV_BUILTIN_MAX,
  RISCV_BUILTIN_MIN,
  RISCV_BUILTIN_SRA8,
  RISCV_BUILTIN_V_SRA8,
  RISCV_BUILTIN_SRA8_U,
  RISCV_BUILTIN_V_SRA8_U,
  RISCV_BUILTIN_SRL8,
  RISCV_BUILTIN_V_SRL8,
  RISCV_BUILTIN_SRL8_U,
  RISCV_BUILTIN_V_SRL8_U,
  RISCV_BUILTIN_SLL8,
  RISCV_BUILTIN_V_SLL8,
  RISCV_BUILTIN_KSLL8,
  RISCV_BUILTIN_V_KSLL8,
  RISCV_BUILTIN_KSLRA8,
  RISCV_BUILTIN_V_KSLRA8,
  RISCV_BUILTIN_KSLRA8_U,
  RISCV_BUILTIN_V_KSLRA8_U,
  RISCV_BUILTIN_CLO,
  RISCV_BUILTIN_CLZ,
  RISCV_BUILTIN_PBSAD,
  RISCV_BUILTIN_PBSADA,
  RISCV_BUILTIN_SWAP16,
  RISCV_BUILTIN_V_SWAP16,
  RISCV_BUILTIN_SWAP8,
  RISCV_BUILTIN_V_SWAP8,
  RISCV_BUILTIN_SCLIP8,
  RISCV_BUILTIN_V_SCLIP8,
  RISCV_BUILTIN_UCLIP8,
  RISCV_BUILTIN_V_UCLIP8,
  RISCV_BUILTIN_FFB,
  RISCV_BUILTIN_FFMISM,
  RISCV_BUILTIN_FLMISM,
  RISCV_BUILTIN_V64_UADD16,
  RISCV_BUILTIN_V64_SADD16,
  RISCV_BUILTIN_V64_RADD16,
  RISCV_BUILTIN_V64_URADD16,
  RISCV_BUILTIN_V64_KADD16,
  RISCV_BUILTIN_V64_UKADD16,
  RISCV_BUILTIN_V64_USUB16,
  RISCV_BUILTIN_V64_SSUB16,
  RISCV_BUILTIN_V64_RSUB16,
  RISCV_BUILTIN_V64_URSUB16,
  RISCV_BUILTIN_V64_KSUB16,
  RISCV_BUILTIN_V64_UKSUB16,
  RISCV_BUILTIN_V64_UADD8,
  RISCV_BUILTIN_V64_SADD8,
  RISCV_BUILTIN_V64_RADD8,
  RISCV_BUILTIN_V64_URADD8,
  RISCV_BUILTIN_V64_KADD8,
  RISCV_BUILTIN_V64_UKADD8,
  RISCV_BUILTIN_V64_USUB8,
  RISCV_BUILTIN_V64_SSUB8,
  RISCV_BUILTIN_V64_RSUB8,
  RISCV_BUILTIN_V64_URSUB8,
  RISCV_BUILTIN_V64_KSUB8,
  RISCV_BUILTIN_V64_UKSUB8,
  RISCV_BUILTIN_V64_UCRAS16,
  RISCV_BUILTIN_V64_SCRAS16,
  RISCV_BUILTIN_V64_RCRAS16,
  RISCV_BUILTIN_V64_URCRAS16,
  RISCV_BUILTIN_V64_KCRAS16,
  RISCV_BUILTIN_V64_UKCRAS16,
  RISCV_BUILTIN_V64_UCRSA16,
  RISCV_BUILTIN_V64_SCRSA16,
  RISCV_BUILTIN_V64_RCRSA16,
  RISCV_BUILTIN_V64_URCRSA16,
  RISCV_BUILTIN_V64_KCRSA16,
  RISCV_BUILTIN_V64_UKCRSA16,
  RISCV_BUILTIN_V64_SRA16,
  RISCV_BUILTIN_V64_SRA16_U,
  RISCV_BUILTIN_V64_SRL16,
  RISCV_BUILTIN_V64_SRL16_U,
  RISCV_BUILTIN_V64_SLL16,
  RISCV_BUILTIN_V64_KSLL16,
  RISCV_BUILTIN_V64_KSLRA16,
  RISCV_BUILTIN_V64_KSLRA16_U,
  RISCV_BUILTIN_V64_SRA8,
  RISCV_BUILTIN_V64_SRA8_U,
  RISCV_BUILTIN_V64_SRL8,
  RISCV_BUILTIN_V64_SRL8_U,
  RISCV_BUILTIN_V64_SLL8,
  RISCV_BUILTIN_V64_KSLL8,
  RISCV_BUILTIN_V64_KSLRA8,
  RISCV_BUILTIN_V64_KSLRA8_U,
  RISCV_BUILTIN_V64_SCMPEQ16,
  RISCV_BUILTIN_V64_UCMPEQ16,
  RISCV_BUILTIN_V64_SCMPLT16,
  RISCV_BUILTIN_V64_SCMPLE16,
  RISCV_BUILTIN_V64_UCMPLT16,
  RISCV_BUILTIN_V64_UCMPLE16,
  RISCV_BUILTIN_V64_SCMPEQ8,
  RISCV_BUILTIN_V64_UCMPEQ8,
  RISCV_BUILTIN_V64_SCMPLT8,
  RISCV_BUILTIN_V64_SCMPLE8,
  RISCV_BUILTIN_V64_UCMPLT8,
  RISCV_BUILTIN_V64_UCMPLE8,
  RISCV_BUILTIN_V64_SMIN16,
  RISCV_BUILTIN_V64_UMIN16,
  RISCV_BUILTIN_V64_SMAX16,
  RISCV_BUILTIN_V64_UMAX16,
  RISCV_BUILTIN_V64_SMIN8,
  RISCV_BUILTIN_V64_UMIN8,
  RISCV_BUILTIN_V64_SMAX8,
  RISCV_BUILTIN_V64_UMAX8,
  RISCV_BUILTIN_V64_SCLIP16,
  RISCV_BUILTIN_V64_UCLIP16,
  RISCV_BUILTIN_V64_SCLIP8,
  RISCV_BUILTIN_V64_UCLIP8,
  RISCV_BUILTIN_V64_KHM16,
  RISCV_BUILTIN_V64_KHMX16,
  RISCV_BUILTIN_V64_KHM8,
  RISCV_BUILTIN_V64_KHMX8,
  RISCV_BUILTIN_DSP_END
};

/* This structure describes a single built-in function.  */
struct riscv_builtin_description {
  /* The code of the main .md file instruction.  See riscv_builtin_type
     for more information.  */
  enum insn_code icode;

  /* The code for RV64 instruction.  */
  enum insn_code icode64;

  /* The name of the built-in function.  */
  const char *name;

  /* Specifies how the function should be expanded.  */
  enum riscv_builtin_type builtin_type;

  /* The function's prototype.  */
  enum riscv_function_type prototype;

  /* Identifies which built-in operation it is.  */
  enum riscv_builtins fcode;
};

/* Construct a riscv_builtin_description from the given arguments.

   INSN is the name of the associated instruction pattern, without the
   leading CODE_FOR_riscv_.

   NAME is the name of the function itself, without the leading
   "__builtin_riscv_".

   BUILTIN_TYPE and FUNCTION_TYPE are riscv_builtin_description fields.

   AVAIL is the name of the availability predicate, without the leading
   riscv_builtin_avail_.  */
#define RISCV_BUILTIN(ICODE, ICODE64, NAME,				\
		      BUILTIN_TYPE, FUNCTION_TYPE, FCODE)		\
  { CODE_FOR_riscv_ ##ICODE, CODE_FOR_riscv_ ##ICODE64,			\
    "__builtin_riscv_" NAME, BUILTIN_TYPE, FUNCTION_TYPE,		\
    RISCV_BUILTIN_ ## FCODE}

#define RISCV_DSP_BUILTIN(ICODE, ICODE64, NAME,				\
			  BUILTIN_TYPE, FUNCTION_TYPE, FCODE)		\
  { CODE_FOR_ ##ICODE, CODE_FOR_ ##ICODE64,				\
    "__builtin_riscv_" NAME, BUILTIN_TYPE, FUNCTION_TYPE,		\
    RISCV_BUILTIN_ ## FCODE}

/* Define __builtin_riscv_<INSN>, which is a RISCV_BUILTIN_DIRECT function
   mapped to instruction CODE_FOR_riscv_<ICODE/ICODE64>, FUNCTION_TYPE
   and AVAIL are as for RISCV_BUILTIN.  */
#define DIRECT_BUILTIN(ICODE, ICODE64, INSN, FUNCTION_TYPE, FCODE)	\
  RISCV_BUILTIN (ICODE, ICODE64, #INSN, RISCV_BUILTIN_DIRECT,		\
		 FUNCTION_TYPE, FCODE)

#define DIRECT_DSP_BUILTIN(ICODE, ICODE64, INSN, FUNCTION_TYPE, FCODE)	\
  RISCV_DSP_BUILTIN (ICODE, ICODE64, #INSN, RISCV_BUILTIN_DIRECT,	\
		     FUNCTION_TYPE, FCODE)

/* Define __builtin_riscv_<INSN>, which is a RISCV_BUILTIN_DIRECT_NO_TARGET
   function mapped to instruction CODE_FOR_riscv_<ICODE/ICODE64>,
   FUNCTION_TYPE and AVAIL are as for RISCV_BUILTIN.  */
#define DIRECT_NO_TARGET_BUILTIN(ICODE, ICODE64, INSN,		\
				 FUNCTION_TYPE, FCODE)		\
  RISCV_BUILTIN (ICODE, ICODE64, #INSN, RISCV_BUILTIN_DIRECT_NO_TARGET,	\
		 FUNCTION_TYPE, FCODE)

/* Argument types.  */
#define RISCV_ATYPE_VOID void_type_node
#define RISCV_ATYPE_SI intSI_type_node
#define RISCV_ATYPE_USI unsigned_intSI_type_node
#define RISCV_ATYPE_ULONG long_unsigned_type_node
#define RISCV_ATYPE_LONG long_integer_type_node
#define RISCV_ATYPE_LLONG long_long_integer_type_node
#define RISCV_ATYPE_ULLONG  long_long_unsigned_type_node
#define RISCV_ATYPE_PSI build_pointer_type (integer_type_node)
#define RISCV_ATYPE_PUSI build_pointer_type (unsigned_type_node)
#define RISCV_ATYPE_PLLONG build_pointer_type (long_long_integer_type_node)
#define RISCV_ATYPE_PULLONG build_pointer_type (long_long_unsigned_type_node)
#define RISCV_ATYPE_V4QI build_vector_type (intQI_type_node, 4)
#define RISCV_ATYPE_UV4QI build_vector_type (unsigned_intQI_type_node, 4)
#define RISCV_ATYPE_V8QI build_vector_type (intQI_type_node, 8)
#define RISCV_ATYPE_UV8QI build_vector_type (unsigned_intQI_type_node, 8)
#define RISCV_ATYPE_V2HI build_vector_type (intHI_type_node, 2)
#define RISCV_ATYPE_UV2HI build_vector_type (unsigned_intHI_type_node, 2)
#define RISCV_ATYPE_V4HI build_vector_type (intHI_type_node, 4)
#define RISCV_ATYPE_UV4HI build_vector_type (unsigned_intHI_type_node, 4)
#define RISCV_ATYPE_V2SI build_vector_type (intSI_type_node, 2)
#define RISCV_ATYPE_UV2SI build_vector_type (unsigned_intSI_type_node, 2)

/* RISCV_FTYPE_ATYPESN takes N RISCV_FTYPES-like type codes and lists
   their associated RISCV_ATYPEs.  */
#define RISCV_FTYPE_ATYPES0(A) \
  RISCV_ATYPE_##A
#define RISCV_FTYPE_ATYPES1(A, B) \
  RISCV_ATYPE_##A, RISCV_ATYPE_##B
#define RISCV_FTYPE_ATYPES2(A, B, C) \
  RISCV_ATYPE_##A, RISCV_ATYPE_##B, RISCV_ATYPE_##C
#define RISCV_FTYPE_ATYPES3(A, B, C, D) \
  RISCV_ATYPE_##A, RISCV_ATYPE_##B, RISCV_ATYPE_##C, RISCV_ATYPE_##D
#define RISCV_FTYPE_ATYPES4(A, B, C, D, E) \
  RISCV_ATYPE_##A, RISCV_ATYPE_##B, RISCV_ATYPE_##C, RISCV_ATYPE_##D, \
  RISCV_ATYPE_##E
#define RISCV_FTYPE_ATYPES5(A, B, C, D, E, F) \
  RISCV_ATYPE_##A, RISCV_ATYPE_##B, RISCV_ATYPE_##C, RISCV_ATYPE_##D, \
  RISCV_ATYPE_##E, RISCV_ATYPE_##F
#define RISCV_FTYPE_ATYPES6(A, B, C, D, E, F, G) \
  RISCV_ATYPE_##A, RISCV_ATYPE_##B, RISCV_ATYPE_##C, RISCV_ATYPE_##D, \
  RISCV_ATYPE_##E, RISCV_ATYPE_##F, RISCV_ATYPE_##G
#define RISCV_FTYPE_ATYPES7(A, B, C, D, E, F, G, H) \
  RISCV_ATYPE_##A, RISCV_ATYPE_##B, RISCV_ATYPE_##C, RISCV_ATYPE_##D, \
  RISCV_ATYPE_##E, RISCV_ATYPE_##F, RISCV_ATYPE_##G, RISCV_ATYPE_##H

static const struct riscv_builtin_description riscv_builtins[] = {
  DIRECT_BUILTIN (frflags, frflags, frflags_fenv,
		  RISCV_USI_FTYPE, FRFLAGS_FENV),
  DIRECT_NO_TARGET_BUILTIN (fsflags, fsflags, fsflags_fenv,
			    RISCV_VOID_FTYPE_USI, FSFLAGS_FENV),
  DIRECT_BUILTIN (csrrsi, csrrdi, csrr,
		  RISCV_ULONG_FTYPE_USI, CSRR),
  DIRECT_NO_TARGET_BUILTIN (csrwsi, csrwdi, csrw,
			    RISCV_VOID_FTYPE_ULONG_USI, CSRW),
  DIRECT_NO_TARGET_BUILTIN (csrssi, csrsdi, csrs,
			    RISCV_VOID_FTYPE_ULONG_USI, CSRS),
  DIRECT_NO_TARGET_BUILTIN (csrcsi, csrcdi, csrc,
			    RISCV_VOID_FTYPE_ULONG_USI, CSRC),
  DIRECT_BUILTIN (get_current_spsi, get_current_spdi, get_current_sp,
		  RISCV_ULONG_FTYPE_VOID, GET_SP),
  DIRECT_NO_TARGET_BUILTIN (set_current_spsi, set_current_spdi, set_current_sp,
			    RISCV_VOID_FTYPE_ULONG, SET_SP),
  DIRECT_BUILTIN (ecallsi, ecalldi, ecall,
		  RISCV_LONG_FTYPE_LONG, ECALL),
  DIRECT_BUILTIN (ecall1si, ecall1di, ecall1,
		  RISCV_LONG_FTYPE_LONG_LONG, ECALL),
  DIRECT_BUILTIN (ecall2si, ecall2di, ecall2,
		  RISCV_LONG_FTYPE_LONG_LONG_LONG, ECALL),
  DIRECT_BUILTIN (ecall3si, ecall3di, ecall3,
		  RISCV_LONG_FTYPE_LONG_LONG_LONG_LONG, ECALL),
  DIRECT_BUILTIN (ecall4si, ecall4di, ecall4,
		  RISCV_LONG_FTYPE_LONG_LONG_LONG_LONG_LONG, ECALL),
  DIRECT_BUILTIN (ecall5si, ecall5di, ecall5,
		  RISCV_LONG_FTYPE_LONG_LONG_LONG_LONG_LONG_LONG,
		  ECALL),
  DIRECT_BUILTIN (ecall6si, ecall6di, ecall6,
		  RISCV_LONG_FTYPE_LONG_LONG_LONG_LONG_LONG_LONG_LONG,
		  ECALL),
  DIRECT_NO_TARGET_BUILTIN (fence, fence, fence,
			    RISCV_VOID_FTYPE_USI_USI, FENCE),
  DIRECT_NO_TARGET_BUILTIN (fencei, fencei, fencei,
			    RISCV_VOID_FTYPE_VOID, FENCEI),
  DIRECT_BUILTIN (frcsr, frcsr, frcsr,
		  RISCV_USI_FTYPE, FRCSR),
  DIRECT_BUILTIN (fscsrsi, fscsrdi, fscsr,
		  RISCV_ULONG_FTYPE_ULONG, FSCSR),
  DIRECT_NO_TARGET_BUILTIN (fwcsrsi, fwcsrdi, fwcsr,
			    RISCV_VOID_FTYPE_ULONG, FWCSR),
  DIRECT_BUILTIN (frrmsi, frrmdi, frrm,
		  RISCV_ULONG_FTYPE_VOID, FRRM),
  DIRECT_BUILTIN (fsrmsi, fsrmdi, fsrm,
		  RISCV_ULONG_FTYPE_ULONG, FSRM),
  DIRECT_NO_TARGET_BUILTIN (fwrmsi, fwrmdi, fwrm,
			    RISCV_VOID_FTYPE_ULONG, FWRM),
  DIRECT_BUILTIN (frflagssi, frflagsdi, frflags,
		  RISCV_ULONG_FTYPE_VOID, FRFLAGS),
  DIRECT_BUILTIN (fsflagssi, fsflagsdi, fsflags,
		  RISCV_ULONG_FTYPE_ULONG, FSFLAGS),
  DIRECT_NO_TARGET_BUILTIN (fwflagssi, fwflagsdi, fwflags,
			    RISCV_VOID_FTYPE_ULONG, FWFLAGS),
  DIRECT_BUILTIN (lrwsi, lrwdi, lrw,
		  RISCV_SI_FTYPE_PSI_USI, LRW),
  DIRECT_BUILTIN (lrd, lrd, lrd,
		  RISCV_LLONG_FTYPE_PLLONG_USI, LRD),
  DIRECT_BUILTIN (scwsi, scwdi, scw,
		  RISCV_SI_FTYPE_SI_PSI_USI, SCW),
  DIRECT_BUILTIN (scd, scd, scd,
		  RISCV_LLONG_FTYPE_LLONG_PLLONG_USI, SCD),
  DIRECT_BUILTIN (amowswapsi, amowswapdi, amoswapw,
		  RISCV_SI_FTYPE_SI_PSI_USI, AMOW),
  DIRECT_BUILTIN (amowaddsi, amowadddi, amoaddw,
		  RISCV_SI_FTYPE_SI_PSI_USI, AMOW),
  DIRECT_BUILTIN (amowminsi, amowmindi, amominw,
		  RISCV_SI_FTYPE_SI_PSI_USI, AMOW),
  DIRECT_BUILTIN (amowmaxsi, amowmaxdi, amomaxw,
		  RISCV_SI_FTYPE_SI_PSI_USI, AMOW),
  DIRECT_BUILTIN (amowxorsi, amowxordi, amoxorw,
		  RISCV_USI_FTYPE_USI_PUSI_USI, AMOW),
  DIRECT_BUILTIN (amowandsi, amowanddi, amoandw,
		  RISCV_USI_FTYPE_USI_PUSI_USI, AMOW),
  DIRECT_BUILTIN (amoworsi, amowordi, amoorw,
		  RISCV_USI_FTYPE_USI_PUSI_USI, AMOW),
  DIRECT_BUILTIN (amowminusi, amowminudi, amominuw,
		  RISCV_USI_FTYPE_USI_PUSI_USI, AMOW),
  DIRECT_BUILTIN (amowmaxusi, amowmaxudi, amomaxuw,
		  RISCV_USI_FTYPE_USI_PUSI_USI, AMOW),
  DIRECT_BUILTIN (amodswap, amodswap, amoswapd,
		  RISCV_LLONG_FTYPE_LLONG_PLLONG_USI, AMOD),
  DIRECT_BUILTIN (amodadd, amodadd, amoaddd,
		  RISCV_LLONG_FTYPE_LLONG_PLLONG_USI, AMOD),
  DIRECT_BUILTIN (amodmin, amodmin, amomind,
		  RISCV_LLONG_FTYPE_LLONG_PLLONG_USI, AMOD),
  DIRECT_BUILTIN (amodmax, amodmax, amomaxd,
		  RISCV_LLONG_FTYPE_LLONG_PLLONG_USI, AMOD),
  DIRECT_BUILTIN (amodxor, amodxor, amoxord,
		  RISCV_ULLONG_FTYPE_ULLONG_PULLONG_USI, AMOD),
  DIRECT_BUILTIN (amodand, amodand, amoandd,
		  RISCV_ULLONG_FTYPE_ULLONG_PULLONG_USI, AMOD),
  DIRECT_BUILTIN (amodor, amodor, amoord,
		  RISCV_ULLONG_FTYPE_ULLONG_PULLONG_USI, AMOD),
  DIRECT_BUILTIN (amodminu, amodminu, amominud,
		  RISCV_ULLONG_FTYPE_ULLONG_PULLONG_USI, AMOD),
  DIRECT_BUILTIN (amodmaxu, amodmaxu, amomaxud,
		  RISCV_ULLONG_FTYPE_ULLONG_PULLONG_USI, AMOD),
  DIRECT_BUILTIN (ebreaksi, ebreakdi, ebreak,
		  RISCV_VOID_FTYPE_ULONG, EBREAK),
  DIRECT_BUILTIN (csrrwsi, csrrwdi, csrrw,
		  RISCV_ULONG_FTYPE_ULONG_USI, CSRRW),
  DIRECT_BUILTIN (csrrssi, csrrsdi, csrrs,
		  RISCV_ULONG_FTYPE_ULONG_USI, CSRRS),
  DIRECT_BUILTIN (csrrcsi, csrrcdi, csrrc,
		  RISCV_ULONG_FTYPE_ULONG_USI, CSRRC),
  DIRECT_DSP_BUILTIN (addv2hi3, addv4hi3, add16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, ADD16),
  DIRECT_DSP_BUILTIN (addv2hi3, addv2hi3, v_uadd16,
		      RISCV_UV2HI_FTYPE_UV2HI_UV2HI, V_UADD16),
  DIRECT_DSP_BUILTIN (addv2hi3, addv2hi3, v_sadd16,
		      RISCV_V2HI_FTYPE_V2HI_V2HI, V_SADD16),
  DIRECT_DSP_BUILTIN (addv4hi3, addv4hi3, v64_uadd16,
		      RISCV_UV4HI_FTYPE_UV4HI_UV4HI, V64_UADD16),
  DIRECT_DSP_BUILTIN (addv4hi3, addv4hi3, v64_sadd16,
		      RISCV_V4HI_FTYPE_V4HI_V4HI, V64_SADD16),
  DIRECT_DSP_BUILTIN (raddv2hi3, raddv4hi3, radd16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, RADD16),
  DIRECT_DSP_BUILTIN (raddv2hi3, raddv2hi3, v_radd16,
		      RISCV_V2HI_FTYPE_V2HI_V2HI, V_RADD16),
  DIRECT_DSP_BUILTIN (raddv4hi3, raddv4hi3, v64_radd16,
		      RISCV_V4HI_FTYPE_V4HI_V4HI, V64_RADD16),
  DIRECT_DSP_BUILTIN (uraddv2hi3, uraddv4hi3, uradd16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, URADD16),
  DIRECT_DSP_BUILTIN (uraddv2hi3, uraddv2hi3, v_uradd16,
		      RISCV_UV2HI_FTYPE_UV2HI_UV2HI, V_URADD16),
  DIRECT_DSP_BUILTIN (uraddv4hi3, uraddv4hi3, v64_uradd16,
		      RISCV_UV4HI_FTYPE_UV4HI_UV4HI, V64_URADD16),
  DIRECT_DSP_BUILTIN (kaddv2hi3, kaddv4hi3, kadd16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, KADD16),
  DIRECT_DSP_BUILTIN (kaddv2hi3, kaddv2hi3, v_kadd16,
		      RISCV_V2HI_FTYPE_V2HI_V2HI, V_KADD16),
  DIRECT_DSP_BUILTIN (kaddv4hi3, kaddv4hi3, v64_kadd16,
		      RISCV_V4HI_FTYPE_V4HI_V4HI, V64_KADD16),
  DIRECT_DSP_BUILTIN (ukaddv2hi3, ukaddv4hi3, ukadd16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, UKADD16),
  DIRECT_DSP_BUILTIN (ukaddv2hi3, ukaddv2hi3, v_ukadd16,
		      RISCV_UV2HI_FTYPE_UV2HI_UV2HI, V_UKADD16),
  DIRECT_DSP_BUILTIN (ukaddv4hi3, ukaddv4hi3, v64_ukadd16,
		      RISCV_UV4HI_FTYPE_UV4HI_UV4HI, V64_UKADD16),
  DIRECT_DSP_BUILTIN (subv2hi3, subv4hi3, sub16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, SUB16),
  DIRECT_DSP_BUILTIN (subv2hi3, subv2hi3, v_usub16,
		      RISCV_UV2HI_FTYPE_UV2HI_UV2HI, V_USUB16),
  DIRECT_DSP_BUILTIN (subv2hi3, subv2hi3, v_ssub16,
		      RISCV_V2HI_FTYPE_V2HI_V2HI, V_SSUB16),
  DIRECT_DSP_BUILTIN (subv4hi3, subv4hi3, v64_usub16,
		      RISCV_UV4HI_FTYPE_UV4HI_UV4HI, V64_USUB16),
  DIRECT_DSP_BUILTIN (subv4hi3, subv4hi3, v64_ssub16,
		      RISCV_V4HI_FTYPE_V4HI_V4HI, V64_SSUB16),
  DIRECT_DSP_BUILTIN (rsubv2hi3, rsubv4hi3, rsub16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, RSUB16),
  DIRECT_DSP_BUILTIN (rsubv2hi3, rsubv2hi3, v_rsub16,
		      RISCV_V2HI_FTYPE_V2HI_V2HI, V_RSUB16),
  DIRECT_DSP_BUILTIN (rsubv4hi3, rsubv4hi3, v64_rsub16,
		      RISCV_V4HI_FTYPE_V4HI_V4HI, V64_RSUB16),
  DIRECT_DSP_BUILTIN (ursubv2hi3, ursubv4hi3, ursub16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, URSUB16),
  DIRECT_DSP_BUILTIN (ursubv2hi3, ursubv2hi3, v_ursub16,
		      RISCV_UV2HI_FTYPE_UV2HI_UV2HI, V_URSUB16),
  DIRECT_DSP_BUILTIN (ursubv4hi3, ursubv4hi3, v64_ursub16,
		      RISCV_UV4HI_FTYPE_UV4HI_UV4HI, V64_URSUB16),
  DIRECT_DSP_BUILTIN (ksubv2hi3, ksubv4hi3, ksub16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, KSUB16),
  DIRECT_DSP_BUILTIN (ksubv2hi3, ksubv2hi3, v_ksub16,
		      RISCV_V2HI_FTYPE_V2HI_V2HI, V_KSUB16),
  DIRECT_DSP_BUILTIN (ksubv4hi3, ksubv4hi3, v64_ksub16,
		      RISCV_V4HI_FTYPE_V4HI_V4HI, V64_KSUB16),
  DIRECT_DSP_BUILTIN (uksubv2hi3, uksubv2hi3, uksub16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, UKSUB16),
  DIRECT_DSP_BUILTIN (uksubv2hi3, uksubv2hi3, v_uksub16,
		      RISCV_UV2HI_FTYPE_UV2HI_UV2HI, V_UKSUB16),
  DIRECT_DSP_BUILTIN (uksubv4hi3, uksubv4hi3, v64_uksub16,
		      RISCV_UV4HI_FTYPE_UV4HI_UV4HI, V64_UKSUB16),
  DIRECT_DSP_BUILTIN (cras16_1, cras16_64, cras16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, CRAS16),
  DIRECT_DSP_BUILTIN (cras16_1, cras16_1, v_ucras16,
		      RISCV_UV2HI_FTYPE_UV2HI_UV2HI, V_UCRAS16),
  DIRECT_DSP_BUILTIN (cras16_64, cras16_64, v64_ucras16,
		      RISCV_UV4HI_FTYPE_UV4HI_UV4HI, V64_UCRAS16),
  DIRECT_DSP_BUILTIN (cras16_1, cras16_1, v_scras16,
		      RISCV_V2HI_FTYPE_V2HI_V2HI, V_SCRAS16),
  DIRECT_DSP_BUILTIN (cras16_64, cras16_64, v64_scras16,
		      RISCV_V4HI_FTYPE_V4HI_V4HI, V64_SCRAS16),
  DIRECT_DSP_BUILTIN (rcras16_1, rcras16_64, rcras16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, RCRAS16),
  DIRECT_DSP_BUILTIN (rcras16_1, rcras16_1, v_rcras16,
		      RISCV_V2HI_FTYPE_V2HI_V2HI, V_RCRAS16),
  DIRECT_DSP_BUILTIN (rcras16_64, rcras16_64, v64_rcras16,
		      RISCV_V4HI_FTYPE_V4HI_V4HI, V64_RCRAS16),
  DIRECT_DSP_BUILTIN (urcras16_1, urcras16_64, urcras16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, URCRAS16),
  DIRECT_DSP_BUILTIN (urcras16_1, urcras16_1, v_urcras16,
		      RISCV_UV2HI_FTYPE_UV2HI_UV2HI, V_URCRAS16),
  DIRECT_DSP_BUILTIN (urcras16_64, urcras16_64, v64_urcras16,
		      RISCV_UV4HI_FTYPE_UV4HI_UV4HI, V64_URCRAS16),
  DIRECT_DSP_BUILTIN (kcras16_1, kcras16_64, kcras16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, KCRAS16),
  DIRECT_DSP_BUILTIN (kcras16_1, kcras16_1, v_kcras16,
		      RISCV_V2HI_FTYPE_V2HI_V2HI, V_KCRAS16),
  DIRECT_DSP_BUILTIN (kcras16_64, kcras16_64, v64_kcras16,
		      RISCV_V4HI_FTYPE_V4HI_V4HI, V64_KCRAS16),
  DIRECT_DSP_BUILTIN (ukcras16_1, ukcras16_64, ukcras16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, UKCRAS16),
  DIRECT_DSP_BUILTIN (ukcras16_1, ukcras16_1, v_ukcras16,
		      RISCV_UV2HI_FTYPE_UV2HI_UV2HI, V_UKCRAS16),
  DIRECT_DSP_BUILTIN (ukcras16_64, ukcras16_64, v64_ukcras16,
		      RISCV_UV4HI_FTYPE_UV4HI_UV4HI, V64_UKCRAS16),
  DIRECT_DSP_BUILTIN (crsa16_1, crsa16_64, crsa16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, CRSA16),
  DIRECT_DSP_BUILTIN (crsa16_1, crsa16_1, v_ucrsa16,
		      RISCV_UV2HI_FTYPE_UV2HI_UV2HI, V_UCRSA16),
  DIRECT_DSP_BUILTIN (crsa16_64, crsa16_64, v64_ucrsa16,
		      RISCV_UV4HI_FTYPE_UV4HI_UV4HI, V64_UCRSA16),
  DIRECT_DSP_BUILTIN (crsa16_1, crsa16_1, v_scrsa16,
		      RISCV_V2HI_FTYPE_V2HI_V2HI, V_SCRSA16),
  DIRECT_DSP_BUILTIN (crsa16_64, crsa16_64, v64_scrsa16,
		      RISCV_V4HI_FTYPE_V4HI_V4HI, V64_SCRSA16),
  DIRECT_DSP_BUILTIN (rcrsa16_1, rcrsa16_64, rcrsa16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, RCRSA16),
  DIRECT_DSP_BUILTIN (rcrsa16_1, rcrsa16_1, v_rcrsa16,
		      RISCV_V2HI_FTYPE_V2HI_V2HI, V_RCRSA16),
  DIRECT_DSP_BUILTIN (rcrsa16_64, rcrsa16_64, v64_rcrsa16,
		      RISCV_V4HI_FTYPE_V4HI_V4HI, V64_RCRSA16),
  DIRECT_DSP_BUILTIN (urcrsa16_1, urcrsa16_64, urcrsa16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, URCRSA16),
  DIRECT_DSP_BUILTIN (urcrsa16_1, urcrsa16_1, v_urcrsa16,
		      RISCV_UV2HI_FTYPE_UV2HI_UV2HI, V_URCRSA16),
  DIRECT_DSP_BUILTIN (urcrsa16_64, urcrsa16_64, v64_urcrsa16,
		      RISCV_UV4HI_FTYPE_UV4HI_UV4HI, V64_URCRSA16),
  DIRECT_DSP_BUILTIN (kcrsa16_1, kcrsa16_64, kcrsa16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, KCRSA16),
  DIRECT_DSP_BUILTIN (kcrsa16_1, kcrsa16_1, v_kcrsa16,
		      RISCV_V2HI_FTYPE_V2HI_V2HI, V_KCRSA16),
  DIRECT_DSP_BUILTIN (kcrsa16_64, kcrsa16_64, v64_kcrsa16,
		      RISCV_V4HI_FTYPE_V4HI_V4HI, V64_KCRSA16),
  DIRECT_DSP_BUILTIN (ukcrsa16_1, ukcrsa16_64, ukcrsa16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, UKCRSA16),
  DIRECT_DSP_BUILTIN (ukcrsa16_1, ukcrsa16_1, v_ukcrsa16,
		      RISCV_UV2HI_FTYPE_UV2HI_UV2HI, V_UKCRSA16),
  DIRECT_DSP_BUILTIN (ukcrsa16_64, ukcrsa16_64, v64_ukcrsa16,
		      RISCV_UV4HI_FTYPE_UV4HI_UV4HI, V64_UKCRSA16),
  /* DSP Extension: SIMD 8bit Add and Subtract.  */
  DIRECT_DSP_BUILTIN (addv4qi3, addv8qi3, add8,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, ADD8),
  DIRECT_DSP_BUILTIN (addv4qi3, addv4qi3, v_uadd8,
		      RISCV_UV4QI_FTYPE_UV4QI_UV4QI, V_UADD8),
  DIRECT_DSP_BUILTIN (addv4qi3, addv4qi3, v_sadd8,
		      RISCV_V4QI_FTYPE_V4QI_V4QI, V_SADD8),
  DIRECT_DSP_BUILTIN (addv8qi3, addv8qi3, v64_uadd8,
		      RISCV_UV8QI_FTYPE_UV8QI_UV8QI, V64_UADD8),
  DIRECT_DSP_BUILTIN (addv8qi3, addv8qi3, v64_sadd8,
		      RISCV_V8QI_FTYPE_V8QI_V8QI, V64_SADD8),
  DIRECT_DSP_BUILTIN (raddv4qi3, raddv8qi3, radd8,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, RADD8),
  DIRECT_DSP_BUILTIN (raddv4qi3, raddv4qi3, v_radd8,
		      RISCV_V4QI_FTYPE_V4QI_V4QI, V_RADD8),
  DIRECT_DSP_BUILTIN (raddv8qi3, raddv8qi3, v64_radd8,
		      RISCV_V8QI_FTYPE_V8QI_V8QI, V64_RADD8),
  DIRECT_DSP_BUILTIN (uraddv4qi3, uraddv8qi3, uradd8,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, URADD8),
  DIRECT_DSP_BUILTIN (uraddv4qi3, uraddv4qi3, v_uradd8,
		      RISCV_UV4QI_FTYPE_UV4QI_UV4QI, V_URADD8),
  DIRECT_DSP_BUILTIN (uraddv8qi3, uraddv8qi3, v64_uradd8,
		      RISCV_UV8QI_FTYPE_UV8QI_UV8QI, V64_URADD8),
  DIRECT_DSP_BUILTIN (kaddv4qi3, kaddv8qi3, kadd8,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, KADD8),
  DIRECT_DSP_BUILTIN (kaddv4qi3, kaddv4qi3, v_kadd8,
		      RISCV_V4QI_FTYPE_V4QI_V4QI, V_KADD8),
  DIRECT_DSP_BUILTIN (kaddv8qi3, kaddv8qi3, v64_kadd8,
		      RISCV_V8QI_FTYPE_V8QI_V8QI, V64_KADD8),
  DIRECT_DSP_BUILTIN (ukaddv4qi3, ukaddv8qi3, ukadd8,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, UKADD8),
  DIRECT_DSP_BUILTIN (ukaddv4qi3, ukaddv4qi3, v_ukadd8,
		      RISCV_UV4QI_FTYPE_UV4QI_UV4QI, V_UKADD8),
  DIRECT_DSP_BUILTIN (ukaddv8qi3, ukaddv8qi3, v64_ukadd8,
		      RISCV_UV8QI_FTYPE_UV8QI_UV8QI, V64_UKADD8),
  DIRECT_DSP_BUILTIN (subv4qi3, subv8qi3, sub8,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, SUB8),
  DIRECT_DSP_BUILTIN (subv4qi3, subv4qi3, v_usub8,
		      RISCV_UV4QI_FTYPE_UV4QI_UV4QI, V_USUB8),
  DIRECT_DSP_BUILTIN (subv4qi3, subv4qi3, v_ssub8,
		      RISCV_V4QI_FTYPE_V4QI_V4QI, V_SSUB8),
  DIRECT_DSP_BUILTIN (subv8qi3, subv8qi3, v64_usub8,
		      RISCV_UV8QI_FTYPE_UV8QI_UV8QI, V64_USUB8),
  DIRECT_DSP_BUILTIN (subv8qi3, subv8qi3, v64_ssub8,
		      RISCV_V8QI_FTYPE_V8QI_V8QI, V64_SSUB8),
  DIRECT_DSP_BUILTIN (rsubv4qi3, rsubv8qi3, rsub8,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, RSUB8),
  DIRECT_DSP_BUILTIN (rsubv4qi3, rsubv4qi3, v_rsub8,
		      RISCV_V4QI_FTYPE_V4QI_V4QI, V_RSUB8),
  DIRECT_DSP_BUILTIN (rsubv8qi3, rsubv8qi3, v64_rsub8,
		      RISCV_V8QI_FTYPE_V8QI_V8QI, V64_RSUB8),
  DIRECT_DSP_BUILTIN (ursubv4qi3, ursubv8qi3, ursub8,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, URSUB8),
  DIRECT_DSP_BUILTIN (ursubv4qi3, ursubv4qi3, v_ursub8,
		      RISCV_UV4QI_FTYPE_UV4QI_UV4QI, V_URSUB8),
  DIRECT_DSP_BUILTIN (ursubv8qi3, ursubv8qi3, v64_ursub8,
		      RISCV_UV8QI_FTYPE_UV8QI_UV8QI, V64_URSUB8),
  DIRECT_DSP_BUILTIN (ksubv4qi3, ksubv8qi3, ksub8,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, KSUB8),
  DIRECT_DSP_BUILTIN (ksubv4qi3, ksubv4qi3, v_ksub8,
		      RISCV_V4QI_FTYPE_V4QI_V4QI, V_KSUB8),
  DIRECT_DSP_BUILTIN (ksubv8qi3, ksubv8qi3, v64_ksub8,
		      RISCV_V8QI_FTYPE_V8QI_V8QI, V64_KSUB8),
  DIRECT_DSP_BUILTIN (uksubv4qi3, uksubv8qi3, uksub8,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, UKSUB8),
  DIRECT_DSP_BUILTIN (uksubv4qi3, uksubv4qi3, v_uksub8,
		      RISCV_UV4QI_FTYPE_UV4QI_UV4QI, V_UKSUB8),
  DIRECT_DSP_BUILTIN (uksubv8qi3, uksubv8qi3, v64_uksub8,
		      RISCV_UV8QI_FTYPE_UV8QI_UV8QI, V64_UKSUB8),
  /* DSP Extension: SIMD 16bit Shift.  */
  DIRECT_DSP_BUILTIN (ashrv2hi3, ashrv4hi3, sra16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, SRA16),
  DIRECT_DSP_BUILTIN (ashrv2hi3, ashrv2hi3, v_sra16,
		      RISCV_V2HI_FTYPE_V2HI_ULONG, V_SRA16),
  DIRECT_DSP_BUILTIN (ashrv4hi3, ashrv4hi3, v64_sra16,
		      RISCV_V4HI_FTYPE_V4HI_ULONG, V64_SRA16),
  DIRECT_DSP_BUILTIN (sra16_roundv2hi, sra16_roundv4hi, sra16_u,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, SRA16_U),
  DIRECT_DSP_BUILTIN (sra16_roundv2hi, sra16_roundv2hi, v_sra16_u,
		      RISCV_V2HI_FTYPE_V2HI_ULONG, V_SRA16_U),
  DIRECT_DSP_BUILTIN (sra16_roundv4hi, sra16_roundv4hi, v64_sra16_u,
		      RISCV_V4HI_FTYPE_V4HI_ULONG, V64_SRA16_U),
  DIRECT_DSP_BUILTIN (lshrv2hi3, lshrv4hi3, srl16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, SRL16),
  DIRECT_DSP_BUILTIN (lshrv2hi3, lshrv2hi3, v_srl16,
		      RISCV_UV2HI_FTYPE_UV2HI_ULONG, V_SRL16),
  DIRECT_DSP_BUILTIN (lshrv4hi3, lshrv4hi3, v64_srl16,
		      RISCV_UV4HI_FTYPE_UV4HI_ULONG, V64_SRL16),
  DIRECT_DSP_BUILTIN (srl16_roundv2hi, srl16_roundv4hi, srl16_u,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, SRL16_U),
  DIRECT_DSP_BUILTIN (srl16_roundv2hi, srl16_roundv2hi, v_srl16_u,
		      RISCV_UV2HI_FTYPE_UV2HI_ULONG, V_SRL16_U),
  DIRECT_DSP_BUILTIN (srl16_roundv4hi, srl16_roundv4hi, v64_srl16_u,
		      RISCV_UV4HI_FTYPE_UV4HI_ULONG, V64_SRL16_U),
  DIRECT_DSP_BUILTIN (ashlv2hi3, ashlv4hi3, sll16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, SLL16),
  DIRECT_DSP_BUILTIN (ashlv2hi3, ashlv2hi3, v_sll16,
		      RISCV_UV2HI_FTYPE_UV2HI_ULONG, V_SLL16),
  DIRECT_DSP_BUILTIN (ashlv4hi3, ashlv4hi3, v64_sll16,
		      RISCV_UV4HI_FTYPE_UV4HI_ULONG, V64_SLL16),
  DIRECT_DSP_BUILTIN (kslli16v2hi, kslli16v4hi, ksll16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, KSLL16),
  DIRECT_DSP_BUILTIN (kslli16v2hi, kslli16v2hi, v_ksll16,
		      RISCV_V2HI_FTYPE_V2HI_ULONG, V_KSLL16),
  DIRECT_DSP_BUILTIN (kslli16v4hi, kslli16v4hi, v64_ksll16,
		      RISCV_V4HI_FTYPE_V4HI_ULONG, V64_KSLL16),
  DIRECT_DSP_BUILTIN (kslrav2hi, kslrav4hi, kslra16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, KSLRA16),
  DIRECT_DSP_BUILTIN (kslrav2hi, kslrav2hi, v_kslra16,
		      RISCV_V2HI_FTYPE_V2HI_ULONG, V_KSLRA16),
  DIRECT_DSP_BUILTIN (kslrav4hi, kslrav4hi, v64_kslra16,
		      RISCV_V4HI_FTYPE_V4HI_ULONG, V64_KSLRA16),
  DIRECT_DSP_BUILTIN (kslrav2hi_round, kslrav4hi_round, kslra16_u,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, KSLRA16_U),
  DIRECT_DSP_BUILTIN (kslrav2hi_round, kslrav2hi_round, v_kslra16_u,
		      RISCV_V2HI_FTYPE_V2HI_ULONG, V_KSLRA16_U),
  DIRECT_DSP_BUILTIN (kslrav4hi_round, kslrav4hi_round, v64_kslra16_u,
		      RISCV_V4HI_FTYPE_V4HI_ULONG, V64_KSLRA16_U),
  /* DSP Extension: 16bit Compare.  */
  DIRECT_DSP_BUILTIN (cmpeqv2hi, cmpeqv4hi, cmpeq16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, CMPEQ16),
  DIRECT_DSP_BUILTIN (cmpeqv2hi, cmpeqv2hi, v_scmpeq16,
		      RISCV_UV2HI_FTYPE_V2HI_V2HI, V_SCMPEQ16),
  DIRECT_DSP_BUILTIN (cmpeqv2hi, cmpeqv2hi, v_ucmpeq16,
		      RISCV_UV2HI_FTYPE_UV2HI_UV2HI, V_UCMPEQ16),
  DIRECT_DSP_BUILTIN (cmpeqv4hi, cmpeqv4hi, v64_scmpeq16,
		      RISCV_UV4HI_FTYPE_V4HI_V4HI, V64_SCMPEQ16),
  DIRECT_DSP_BUILTIN (cmpeqv4hi, cmpeqv4hi, v64_ucmpeq16,
		      RISCV_UV4HI_FTYPE_UV4HI_UV4HI, V64_UCMPEQ16),
  DIRECT_DSP_BUILTIN (scmpltv2hi, scmpltv4hi, scmplt16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, SCMPLT16),
  DIRECT_DSP_BUILTIN (scmpltv2hi, scmpltv2hi, v_scmplt16,
		      RISCV_UV2HI_FTYPE_V2HI_V2HI, V_SCMPLT16),
  DIRECT_DSP_BUILTIN (scmpltv4hi, scmpltv4hi, v64_scmplt16,
		      RISCV_UV4HI_FTYPE_V4HI_V4HI, V64_SCMPLT16),
  DIRECT_DSP_BUILTIN (scmplev2hi, scmplev4hi, scmple16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, SCMPLE16),
  DIRECT_DSP_BUILTIN (scmplev2hi, scmplev2hi, v_scmple16,
		      RISCV_UV2HI_FTYPE_V2HI_V2HI, V_SCMPLE16),
  DIRECT_DSP_BUILTIN (scmplev4hi, scmplev4hi, v64_scmple16,
		      RISCV_UV4HI_FTYPE_V4HI_V4HI, V64_SCMPLE16),
  DIRECT_DSP_BUILTIN (ucmpltv2hi, ucmpltv4hi, ucmplt16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, UCMPLT16),
  DIRECT_DSP_BUILTIN (ucmpltv2hi, ucmpltv2hi, v_ucmplt16,
		      RISCV_UV2HI_FTYPE_UV2HI_UV2HI, V_UCMPLT16),
  DIRECT_DSP_BUILTIN (ucmpltv4hi, ucmpltv4hi, v64_ucmplt16,
		      RISCV_UV4HI_FTYPE_UV4HI_UV4HI, V64_UCMPLT16),
  DIRECT_DSP_BUILTIN (ucmplev2hi, ucmplev4hi, ucmple16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, UCMPLE16),
  DIRECT_DSP_BUILTIN (ucmplev2hi, ucmplev2hi, v_ucmple16,
		      RISCV_UV2HI_FTYPE_UV2HI_UV2HI, V_UCMPLE16),
  DIRECT_DSP_BUILTIN (ucmplev4hi, ucmplev4hi, v64_ucmple16,
		      RISCV_UV4HI_FTYPE_UV4HI_UV4HI, V64_UCMPLE16),

  /* DSP Extension: 8bit Compare.  */
  DIRECT_DSP_BUILTIN (cmpeqv4qi, cmpeqv8qi, cmpeq8,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, CMPEQ8),
  DIRECT_DSP_BUILTIN (cmpeqv4qi, cmpeqv4qi, v_scmpeq8,
		      RISCV_UV4QI_FTYPE_V4QI_V4QI, V_SCMPEQ8),
  DIRECT_DSP_BUILTIN (cmpeqv4qi, cmpeqv4qi, v_ucmpeq8,
		      RISCV_UV4QI_FTYPE_UV4QI_UV4QI, V_UCMPEQ8),
  DIRECT_DSP_BUILTIN (cmpeqv8qi, cmpeqv8qi, v64_scmpeq8,
		      RISCV_UV8QI_FTYPE_V8QI_V8QI, V64_SCMPEQ8),
  DIRECT_DSP_BUILTIN (cmpeqv8qi, cmpeqv8qi, v64_ucmpeq8,
		      RISCV_UV8QI_FTYPE_UV8QI_UV8QI, V64_UCMPEQ8),
  DIRECT_DSP_BUILTIN (scmpltv4qi, scmpltv8qi, scmplt8,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, SCMPLT8),
  DIRECT_DSP_BUILTIN (scmpltv4qi, scmpltv4qi, v_scmplt8,
		      RISCV_UV4QI_FTYPE_V4QI_V4QI, V_SCMPLT8),
  DIRECT_DSP_BUILTIN (scmpltv8qi, scmpltv8qi, v64_scmplt8,
		      RISCV_UV8QI_FTYPE_V8QI_V8QI, V64_SCMPLT8),
  DIRECT_DSP_BUILTIN (scmplev4qi, scmplev8qi, scmple8,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, SCMPLE8),
  DIRECT_DSP_BUILTIN (scmplev4qi, scmplev4qi, v_scmple8,
		      RISCV_UV4QI_FTYPE_V4QI_V4QI, V_SCMPLE8),
  DIRECT_DSP_BUILTIN (scmplev8qi, scmplev8qi, v64_scmple8,
		      RISCV_UV8QI_FTYPE_V8QI_V8QI, V64_SCMPLE8),
  DIRECT_DSP_BUILTIN (ucmpltv4qi, ucmpltv8qi, ucmplt8,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, UCMPLT8),
  DIRECT_DSP_BUILTIN (ucmpltv4qi, ucmpltv8qi, v_ucmplt8,
		      RISCV_UV4QI_FTYPE_UV4QI_UV4QI, V_UCMPLT8),
  DIRECT_DSP_BUILTIN (ucmpltv8qi, ucmpltv8qi, v64_ucmplt8,
		      RISCV_UV8QI_FTYPE_UV8QI_UV8QI, V64_UCMPLT8),
  DIRECT_DSP_BUILTIN (ucmplev4qi, ucmplev8qi, ucmple8,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, UCMPLE8),
  DIRECT_DSP_BUILTIN (ucmplev4qi, ucmplev4qi, v_ucmple8,
		      RISCV_UV4QI_FTYPE_UV4QI_UV4QI, V_UCMPLE8),
  DIRECT_DSP_BUILTIN (ucmplev8qi, ucmplev8qi, v64_ucmple8,
		      RISCV_UV8QI_FTYPE_UV8QI_UV8QI, V64_UCMPLE8),
  /* DSP Extension: SIMD 16bit MISC.  */
  DIRECT_DSP_BUILTIN (sminv2hi3, sminv4hi3, smin16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, SMIN16),
  DIRECT_DSP_BUILTIN (sminv2hi3, sminv2hi3, v_smin16,
		      RISCV_V2HI_FTYPE_V2HI_V2HI, V_SMIN16),
  DIRECT_DSP_BUILTIN (sminv4hi3, sminv4hi3, v64_smin16,
		      RISCV_V4HI_FTYPE_V4HI_V4HI, V64_SMIN16),
  DIRECT_DSP_BUILTIN (uminv2hi3, uminv4hi3, umin16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, UMIN16),
  DIRECT_DSP_BUILTIN (uminv2hi3, uminv2hi3, v_umin16,
		      RISCV_UV2HI_FTYPE_UV2HI_UV2HI, V_UMIN16),
  DIRECT_DSP_BUILTIN (uminv4hi3, uminv4hi3, v64_umin16,
		      RISCV_UV4HI_FTYPE_UV4HI_UV4HI, V64_UMIN16),
  DIRECT_DSP_BUILTIN (smaxv2hi3, smaxv4hi3, smax16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, SMAX16),
  DIRECT_DSP_BUILTIN (smaxv2hi3, smaxv2hi3, v_smax16,
		      RISCV_V2HI_FTYPE_V2HI_V2HI, V_SMAX16),
  DIRECT_DSP_BUILTIN (smaxv4hi3, smaxv4hi3, v64_smax16,
		      RISCV_V4HI_FTYPE_V4HI_V4HI, V64_SMAX16),
  DIRECT_DSP_BUILTIN (umaxv2hi3, umaxv4hi3, umax16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, UMAX16),
  DIRECT_DSP_BUILTIN (umaxv2hi3, umaxv2hi3, v_umax16,
		      RISCV_UV2HI_FTYPE_UV2HI_UV2HI, V_UMAX16),
  DIRECT_DSP_BUILTIN (umaxv4hi3, umaxv4hi3, v64_umax16,
		      RISCV_UV4HI_FTYPE_UV4HI_UV4HI, V64_UMAX16),
  DIRECT_DSP_BUILTIN (sclip16v2hi, sclip16v4hi, sclip16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, SCLIP16),
  DIRECT_DSP_BUILTIN (sclip16v2hi, sclip16v2hi, v_sclip16,
		      RISCV_V2HI_FTYPE_V2HI_ULONG, V_SCLIP16),
  DIRECT_DSP_BUILTIN (sclip16v4hi, sclip16v4hi, v64_sclip16,
		      RISCV_V4HI_FTYPE_V4HI_ULONG, V64_SCLIP16),
  DIRECT_DSP_BUILTIN (uclip16v2hi, uclip16v4hi, uclip16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, UCLIP16),
  DIRECT_DSP_BUILTIN (uclip16v2hi, uclip16v2hi, v_uclip16,
		      RISCV_V2HI_FTYPE_V2HI_ULONG, V_UCLIP16),
  DIRECT_DSP_BUILTIN (uclip16v4hi, uclip16v4hi, v64_uclip16,
		      RISCV_V4HI_FTYPE_V4HI_ULONG, V64_UCLIP16),
  DIRECT_DSP_BUILTIN (khm16v2hi, khm16v4hi, khm16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, KHM16),
  DIRECT_DSP_BUILTIN (khm16v2hi, khm16v2hi, v_khm16,
		      RISCV_V2HI_FTYPE_V2HI_V2HI, V_KHM16),
  DIRECT_DSP_BUILTIN (khm16v4hi, khm16v4hi, v64_khm16,
		      RISCV_V4HI_FTYPE_V4HI_V4HI, V64_KHM16),
  DIRECT_DSP_BUILTIN (khmx16v2hi, khmx16v4hi, khmx16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, KHMX16),
  DIRECT_DSP_BUILTIN (khmx16v2hi, khmx16v2hi, v_khmx16,
		      RISCV_V2HI_FTYPE_V2HI_V2HI, V_KHMX16),
  DIRECT_DSP_BUILTIN (khmx16v4hi, khmx16v4hi, v64_khmx16,
		      RISCV_V4HI_FTYPE_V4HI_V4HI, V64_KHMX16),
  DIRECT_DSP_BUILTIN (khm8v4qi, khm8v8qi, khm8,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, KHM8),
  DIRECT_DSP_BUILTIN (khm8v4qi, khm8v4qi, v_khm8,
		      RISCV_V4QI_FTYPE_V4QI_V4QI, V_KHM8),
  DIRECT_DSP_BUILTIN (khm8v8qi, khm8v8qi, v64_khm8,
		      RISCV_V8QI_FTYPE_V8QI_V8QI, V64_KHM8),
  DIRECT_DSP_BUILTIN (khmx8v4qi, khmx8v8qi, khmx8,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, KHMX8),
  DIRECT_DSP_BUILTIN (khmx8v4qi, khmx8v4qi, v_khmx8,
		      RISCV_V4QI_FTYPE_V4QI_V4QI, V_KHMX8),
  DIRECT_DSP_BUILTIN (khmx8v8qi, khmx8v8qi, v64_khmx8,
		      RISCV_V8QI_FTYPE_V8QI_V8QI, V64_KHMX8),
  DIRECT_DSP_BUILTIN (kabsv2hi2, kabsv2hi2, kabs16,
		      RISCV_ULONG_FTYPE_ULONG, KABS16),
  DIRECT_DSP_BUILTIN (kabsv2hi2, kabsv2hi2, v_kabs16,
		      RISCV_V2HI_FTYPE_V2HI, V_KABS16),
  DIRECT_DSP_BUILTIN (smul16, smul16, smul16,
		      RISCV_ULLONG_FTYPE_USI_USI, SMUL16),
  DIRECT_DSP_BUILTIN (smul16, smul16, v_smul16,
		      RISCV_V2SI_FTYPE_V2HI_V2HI, V_SMUL16),
  DIRECT_DSP_BUILTIN (smulx16, smulx16, smulx16,
		      RISCV_ULLONG_FTYPE_USI_USI, SMULX16),
  DIRECT_DSP_BUILTIN (smulx16, smulx16, v_smulx16,
		      RISCV_V2SI_FTYPE_V2HI_V2HI, V_SMULX16),
  DIRECT_DSP_BUILTIN (smul8, smul8, smul8,
		      RISCV_ULLONG_FTYPE_USI_USI, SMUL8),
  DIRECT_DSP_BUILTIN (smul8, smul8, v_smul8,
		      RISCV_V4HI_FTYPE_V4QI_V4QI, V_SMUL8),
  DIRECT_DSP_BUILTIN (smulx8, smulx8, smulx8,
		      RISCV_ULLONG_FTYPE_USI_USI, SMULX8),
  DIRECT_DSP_BUILTIN (smulx8, smulx8, v_smulx8,
		      RISCV_V4HI_FTYPE_V4QI_V4QI, V_SMULX8),
  DIRECT_DSP_BUILTIN (umul16, umul16, umul16,
		      RISCV_ULLONG_FTYPE_USI_USI, UMUL16),
  DIRECT_DSP_BUILTIN (umul16, umul16, v_umul16,
		      RISCV_UV2SI_FTYPE_UV2HI_UV2HI, V_UMUL16),
  DIRECT_DSP_BUILTIN (umulx16, umulx16, umulx16,
		      RISCV_ULLONG_FTYPE_USI_USI, UMULX16),
  DIRECT_DSP_BUILTIN (umulx16, umulx16, v_umulx16,
		      RISCV_UV2SI_FTYPE_UV2HI_UV2HI, V_UMULX16),
  DIRECT_DSP_BUILTIN (umul8, umul8, umul8,
		      RISCV_ULLONG_FTYPE_USI_USI, UMUL8),
  DIRECT_DSP_BUILTIN (umul8, umul8, v_umul8,
		      RISCV_UV4HI_FTYPE_UV4QI_UV4QI, V_UMUL8),
  DIRECT_DSP_BUILTIN (umulx8, umulx8, umulx8,
		      RISCV_ULLONG_FTYPE_USI_USI, UMULX8),
  DIRECT_DSP_BUILTIN (umulx8, umulx8, v_umulx8,
		      RISCV_UV4HI_FTYPE_UV4QI_UV4QI, V_UMULX8),
  /* DSP Extension: SIMD 8bit MISC.  */
  DIRECT_DSP_BUILTIN (sminv4qi3, sminv8qi3, smin8,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, SMIN8),
  DIRECT_DSP_BUILTIN (sminv4qi3, sminv4qi3, v_smin8,
		      RISCV_V4QI_FTYPE_V4QI_V4QI, V_SMIN8),
  DIRECT_DSP_BUILTIN (sminv8qi3, sminv8qi3, v64_smin8,
		      RISCV_V8QI_FTYPE_V8QI_V8QI, V64_SMIN8),
  DIRECT_DSP_BUILTIN (uminv4qi3, uminv8qi3, umin8,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, UMIN8),
  DIRECT_DSP_BUILTIN (uminv4qi3, uminv4qi3, v_umin8,
		      RISCV_UV4QI_FTYPE_UV4QI_UV4QI, V_UMIN8),
  DIRECT_DSP_BUILTIN (uminv8qi3, uminv8qi3, v64_umin8,
		      RISCV_UV8QI_FTYPE_UV8QI_UV8QI, V64_UMIN8),
  DIRECT_DSP_BUILTIN (smaxv4qi3, smaxv8qi3, smax8,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, SMAX8),
  DIRECT_DSP_BUILTIN (smaxv4qi3, smaxv4qi3, v_smax8,
		      RISCV_V4QI_FTYPE_V4QI_V4QI, V_SMAX8),
  DIRECT_DSP_BUILTIN (smaxv8qi3, smaxv8qi3, v64_smax8,
		      RISCV_V8QI_FTYPE_V8QI_V8QI, V64_SMAX8),
  DIRECT_DSP_BUILTIN (umaxv4qi3, umaxv8qi3, umax8,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, UMAX8),
  DIRECT_DSP_BUILTIN (umaxv4qi3, umaxv4qi3, v_umax8,
		      RISCV_UV4QI_FTYPE_UV4QI_UV4QI, V_UMAX8),
  DIRECT_DSP_BUILTIN (umaxv8qi3, umaxv8qi3, v64_umax8,
		      RISCV_UV8QI_FTYPE_UV8QI_UV8QI, V64_UMAX8),
  DIRECT_DSP_BUILTIN (kabsv4qi2, kabsv4qi2, kabs8,
		      RISCV_ULONG_FTYPE_ULONG, KABS8),
  DIRECT_DSP_BUILTIN (kabsv4qi2, kabsv4qi2, v_kabs8,
		      RISCV_V2HI_FTYPE_V2HI, V_KABS8),
  /* DSP Extension: 8bit Unpacking.  */
  DIRECT_DSP_BUILTIN (sunpkd810, sunpkd810, sunpkd810,
		      RISCV_ULONG_FTYPE_ULONG, SUNPKD810),
  DIRECT_DSP_BUILTIN (sunpkd810, sunpkd810, v_sunpkd810,
		      RISCV_V2HI_FTYPE_V4QI, V_SUNPKD810),
  DIRECT_DSP_BUILTIN (sunpkd820, sunpkd820, sunpkd820,
		      RISCV_ULONG_FTYPE_ULONG, SUNPKD820),
  DIRECT_DSP_BUILTIN (sunpkd820, sunpkd820, v_sunpkd820,
		      RISCV_V2HI_FTYPE_V4QI, V_SUNPKD820),
  DIRECT_DSP_BUILTIN (sunpkd830, sunpkd830, sunpkd830,
		      RISCV_ULONG_FTYPE_ULONG, SUNPKD830),
  DIRECT_DSP_BUILTIN (sunpkd830, sunpkd830, v_sunpkd830,
		      RISCV_V2HI_FTYPE_V4QI, V_SUNPKD830),
  DIRECT_DSP_BUILTIN (sunpkd831, sunpkd831, sunpkd831,
		      RISCV_ULONG_FTYPE_ULONG, SUNPKD831),
  DIRECT_DSP_BUILTIN (sunpkd831, sunpkd831, v_sunpkd831,
		      RISCV_V2HI_FTYPE_V4QI, V_SUNPKD831),
  DIRECT_DSP_BUILTIN (sunpkd832, sunpkd832, sunpkd832,
		      RISCV_ULONG_FTYPE_ULONG, SUNPKD832),
  DIRECT_DSP_BUILTIN (sunpkd832, sunpkd832, v_sunpkd832,
		      RISCV_V2HI_FTYPE_V4QI, V_SUNPKD832),
  DIRECT_DSP_BUILTIN (zunpkd810, zunpkd810, zunpkd810,
		      RISCV_ULONG_FTYPE_ULONG, ZUNPKD810),
  DIRECT_DSP_BUILTIN (zunpkd810, zunpkd810, v_zunpkd810,
		      RISCV_UV2HI_FTYPE_UV4QI, V_ZUNPKD810),
  DIRECT_DSP_BUILTIN (zunpkd820, zunpkd820, zunpkd820,
		      RISCV_ULONG_FTYPE_ULONG, ZUNPKD810),
  DIRECT_DSP_BUILTIN (zunpkd820, zunpkd820, v_zunpkd820,
		      RISCV_UV2HI_FTYPE_UV4QI, V_ZUNPKD810),
  DIRECT_DSP_BUILTIN (zunpkd830, zunpkd830, zunpkd830,
		      RISCV_ULONG_FTYPE_ULONG, ZUNPKD830),
  DIRECT_DSP_BUILTIN (zunpkd830, zunpkd830, v_zunpkd830,
		      RISCV_UV2HI_FTYPE_UV4QI, V_ZUNPKD830),
  DIRECT_DSP_BUILTIN (zunpkd831, zunpkd831, zunpkd831,
		      RISCV_ULONG_FTYPE_ULONG, ZUNPKD831),
  DIRECT_DSP_BUILTIN (zunpkd831, zunpkd831, v_zunpkd831,
		      RISCV_UV2HI_FTYPE_UV4QI, V_ZUNPKD831),
  DIRECT_DSP_BUILTIN (zunpkd832, zunpkd832, zunpkd832,
		      RISCV_ULONG_FTYPE_ULONG, ZUNPKD832),
  DIRECT_DSP_BUILTIN (zunpkd832, zunpkd832, v_zunpkd832,
		      RISCV_UV2HI_FTYPE_UV4QI, V_ZUNPKD832),
  /* DSP Extension: 32bit Add and Subtract.  */
  DIRECT_DSP_BUILTIN (raddsi3, raddsi3, raddw,
		      RISCV_LONG_FTYPE_LONG_LONG, RADDW),
  DIRECT_DSP_BUILTIN (uraddsi3, uraddsi3, uraddw,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, URADDW),
  DIRECT_DSP_BUILTIN (rsubsi3, rsubsi3, rsubw,
		      RISCV_LONG_FTYPE_LONG_LONG, RSUBW),
  DIRECT_DSP_BUILTIN (ursubsi3, ursubsi3, ursubw,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, URSUBW),
  /* DSP Extension: 32bit Shift.  */
  DIRECT_DSP_BUILTIN (sraiu, sraiu, sra_u,
		      RISCV_LONG_FTYPE_LONG_ULONG, SRA_U),
  DIRECT_DSP_BUILTIN (kssl, kssl, ksll,
		      RISCV_LONG_FTYPE_LONG_ULONG, KSLL),
  /* DSP Extension: 16bit Packing.  */
  DIRECT_DSP_BUILTIN (pkbb, pkbb, pkbb16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, PKBB16),
  DIRECT_DSP_BUILTIN (pkbb, pkbb, v_pkbb16,
		      RISCV_UV2HI_FTYPE_UV2HI_UV2HI, V_PKBB16),
  DIRECT_DSP_BUILTIN (pkbt, pkbt, pkbt16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, PKBT16),
  DIRECT_DSP_BUILTIN (pkbt, pkbt, v_pkbt16,
		      RISCV_UV2HI_FTYPE_UV2HI_UV2HI, V_PKBT16),
  DIRECT_DSP_BUILTIN (pktb, pktb, pktb16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, PKTB16),
  DIRECT_DSP_BUILTIN (pktb, pktb, v_pktb16,
		      RISCV_UV2HI_FTYPE_UV2HI_UV2HI, V_PKTB16),
  DIRECT_DSP_BUILTIN (pktt, pktt, pktt16,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, PKTT16),
  DIRECT_DSP_BUILTIN (pktt, pktt, v_pktt16,
		      RISCV_UV2HI_FTYPE_UV2HI_UV2HI, V_PKTT16),
  /* DSP Extension: Signed MSW 32x32 Multiply and ADD.  */
  DIRECT_DSP_BUILTIN (smulsi3_highpart, smulsi3_highpart, smmul,
		      RISCV_LONG_FTYPE_LONG_LONG, SMMUL),
  DIRECT_DSP_BUILTIN (smmul_round, smmul_round, smmul_u,
		      RISCV_LONG_FTYPE_LONG_LONG, SMMUL_U),
  DIRECT_DSP_BUILTIN (kmmac, kmmac, kmmac,
		      RISCV_LONG_FTYPE_LONG_LONG_LONG, KMMAC),
  DIRECT_DSP_BUILTIN (kmmac_round, kmmac_round, kmmac_u,
		      RISCV_LONG_FTYPE_LONG_LONG_LONG, KMMAC_U),
  DIRECT_DSP_BUILTIN (kmmsb, kmmsb, kmmsb,
		      RISCV_LONG_FTYPE_LONG_LONG_LONG, KMMSB),
  DIRECT_DSP_BUILTIN (kmmsb_round, kmmsb_round, kmmsb_u,
		      RISCV_LONG_FTYPE_LONG_LONG_LONG, KMMSB_U),
  DIRECT_DSP_BUILTIN (kwmmul, kwmmul, kwmmul,
		      RISCV_LONG_FTYPE_LONG_LONG, KWMMUL),
  DIRECT_DSP_BUILTIN (kwmmul_round, kwmmul_round, kwmmul_u,
		      RISCV_LONG_FTYPE_LONG_LONG, KWMMUL_U),
  /* DSP Extension: Most Significant Word 32x16 Multiply and ADD.  */
  DIRECT_DSP_BUILTIN (smmwb, smmwb, smmwb,
		      RISCV_LONG_FTYPE_LONG_ULONG, SMMWB),
  DIRECT_DSP_BUILTIN (smmwb, smmwb, v_smmwb,
		      RISCV_LONG_FTYPE_LONG_V2HI, V_SMMWB),
  DIRECT_DSP_BUILTIN (smmwb_round, smmwb_round, smmwb_u,
		      RISCV_LONG_FTYPE_LONG_ULONG, SMMWB_U),
  DIRECT_DSP_BUILTIN (smmwb_round, smmwb_round, v_smmwb_u,
		      RISCV_LONG_FTYPE_LONG_V2HI, V_SMMWB_U),
  DIRECT_DSP_BUILTIN (smmwt, smmwt, smmwt,
		      RISCV_LONG_FTYPE_LONG_ULONG, SMMWT),
  DIRECT_DSP_BUILTIN (smmwt, smmwt, v_smmwt,
		      RISCV_LONG_FTYPE_LONG_V2HI, V_SMMWT),
  DIRECT_DSP_BUILTIN (smmwt_round, smmwt_round, smmwt_u,
		      RISCV_LONG_FTYPE_LONG_ULONG, SMMWT_U),
  DIRECT_DSP_BUILTIN (smmwt_round, smmwt_round, v_smmwt_u,
		      RISCV_LONG_FTYPE_LONG_V2HI, V_SMMWT_U),
  DIRECT_DSP_BUILTIN (kmmawb,kmmawb, kmmawb,
		      RISCV_LONG_FTYPE_LONG_LONG_ULONG, KMMAWB),
  DIRECT_DSP_BUILTIN (kmmawb,kmmawb, v_kmmawb,
		      RISCV_LONG_FTYPE_LONG_LONG_V2HI, V_KMMAWB),
  DIRECT_DSP_BUILTIN (kmmawb_round, kmmawb_round, kmmawb_u,
		      RISCV_LONG_FTYPE_LONG_LONG_ULONG, KMMAWB_U),
  DIRECT_DSP_BUILTIN (kmmawb_round, kmmawb_round, v_kmmawb_u,
		      RISCV_LONG_FTYPE_LONG_LONG_V2HI, V_KMMAWB_U),
  DIRECT_DSP_BUILTIN (kmmawt,kmmawt, kmmawt,
		      RISCV_LONG_FTYPE_LONG_LONG_ULONG, KMMAWT),
  DIRECT_DSP_BUILTIN (kmmawt,kmmawt, v_kmmawt,
		      RISCV_LONG_FTYPE_LONG_LONG_V2HI, V_KMMAWT),
  DIRECT_DSP_BUILTIN (kmmawt_round, kmmawt_round, kmmawt_u,
		      RISCV_LONG_FTYPE_LONG_LONG_ULONG, KMMAWT_U),
  DIRECT_DSP_BUILTIN (kmmawt_round, kmmawt_round, v_kmmawt_u,
		      RISCV_LONG_FTYPE_LONG_LONG_V2HI, V_KMMAWT_U),
  /* DSP Extension: Signed 16bit Multiply with ADD/Subtract.  */
  DIRECT_DSP_BUILTIN (smbb, smbb, smbb,
		      RISCV_LONG_FTYPE_ULONG_ULONG, SMBB),
  DIRECT_DSP_BUILTIN (smbb, smbb, v_smbb,
		      RISCV_LONG_FTYPE_V2HI_V2HI, V_SMBB),
  DIRECT_DSP_BUILTIN (smbt, smbt, smbt,
		      RISCV_LONG_FTYPE_ULONG_ULONG, SMBT),
  DIRECT_DSP_BUILTIN (smbt, smbt, v_smbt,
		      RISCV_LONG_FTYPE_V2HI_V2HI, V_SMBT),
  DIRECT_DSP_BUILTIN (smtt, smtt, smtt,
		      RISCV_LONG_FTYPE_ULONG_ULONG, SMTT),
  DIRECT_DSP_BUILTIN (smtt, smtt, v_smtt,
		      RISCV_LONG_FTYPE_V2HI_V2HI, V_SMTT),
  DIRECT_DSP_BUILTIN (kmda, kmda, kmda,
		      RISCV_LONG_FTYPE_ULONG_ULONG, KMDA),
  DIRECT_DSP_BUILTIN (kmda, kmda, v_kmda,
		      RISCV_LONG_FTYPE_V2HI_V2HI, V_KMDA),
  DIRECT_DSP_BUILTIN (kmxda, kmxda, kmxda,
		      RISCV_LONG_FTYPE_ULONG_ULONG, KMXDA),
  DIRECT_DSP_BUILTIN (kmxda, kmxda, v_kmxda,
		      RISCV_LONG_FTYPE_V2HI_V2HI, V_KMXDA),
  DIRECT_DSP_BUILTIN (smds, smds, smds,
		      RISCV_LONG_FTYPE_ULONG_ULONG, SMDS),
  DIRECT_DSP_BUILTIN (smds, smds, v_smds,
		      RISCV_LONG_FTYPE_V2HI_V2HI, V_SMDS),
  DIRECT_DSP_BUILTIN (smdrs, smdrs, smdrs,
		      RISCV_LONG_FTYPE_ULONG_ULONG, SMDRS),
  DIRECT_DSP_BUILTIN (smdrs, smdrs, v_smdrs,
		      RISCV_LONG_FTYPE_V2HI_V2HI, V_SMDRS),
  DIRECT_DSP_BUILTIN (smxdsv, smxdsv, smxds,
		      RISCV_LONG_FTYPE_ULONG_ULONG, SMXDS),
  DIRECT_DSP_BUILTIN (smxdsv, smxdsv, v_smxds,
		      RISCV_LONG_FTYPE_V2HI_V2HI, V_SMXDS),
  DIRECT_DSP_BUILTIN (kmabb, kmabb, kmabb,
		      RISCV_LONG_FTYPE_LONG_ULONG_ULONG, KMABB),
  DIRECT_DSP_BUILTIN (kmabb, kmabb, v_kmabb,
		      RISCV_LONG_FTYPE_LONG_V2HI_V2HI, V_KMABB),
  DIRECT_DSP_BUILTIN (kmabt, kmabt, kmabt,
		      RISCV_LONG_FTYPE_LONG_ULONG_ULONG, KMABT),
  DIRECT_DSP_BUILTIN (kmabt, kmabt, v_kmabt,
		      RISCV_LONG_FTYPE_LONG_V2HI_V2HI, V_KMABT),
  DIRECT_DSP_BUILTIN (kmatt, kmatt, kmatt,
		      RISCV_LONG_FTYPE_LONG_ULONG_ULONG, KMATT),
  DIRECT_DSP_BUILTIN (kmatt, kmatt, v_kmatt,
		      RISCV_LONG_FTYPE_LONG_V2HI_V2HI, V_KMATT),
  DIRECT_DSP_BUILTIN (kmada, kmada, kmada,
		      RISCV_LONG_FTYPE_LONG_ULONG_ULONG, KMADA),
  DIRECT_DSP_BUILTIN (kmada, kmada, v_kmada,
		      RISCV_LONG_FTYPE_LONG_V2HI_V2HI, V_KMADA),
  DIRECT_DSP_BUILTIN (kmaxda, kmaxda, kmaxda,
		      RISCV_LONG_FTYPE_LONG_ULONG_ULONG, KMAXDA),
  DIRECT_DSP_BUILTIN (kmaxda, kmaxda, v_kmaxda,
		      RISCV_LONG_FTYPE_LONG_V2HI_V2HI, V_KMAXDA),
  DIRECT_DSP_BUILTIN (kmads, kmads, kmads,
		      RISCV_LONG_FTYPE_LONG_ULONG_ULONG, KMADS),
  DIRECT_DSP_BUILTIN (kmads, kmads, v_kmads,
		      RISCV_LONG_FTYPE_LONG_V2HI_V2HI, V_KMADS),
  DIRECT_DSP_BUILTIN (kmadrs, kmadrs, kmadrs,
		      RISCV_LONG_FTYPE_LONG_ULONG_ULONG, KMADRS),
  DIRECT_DSP_BUILTIN (kmadrs, kmadrs, v_kmadrs,
		      RISCV_LONG_FTYPE_LONG_V2HI_V2HI, V_KMADRS),
  DIRECT_DSP_BUILTIN (kmaxds, kmaxds, kmaxds,
		      RISCV_LONG_FTYPE_LONG_ULONG_ULONG, KMAXDS),
  DIRECT_DSP_BUILTIN (kmaxds, kmaxds, v_kmaxds,
		      RISCV_LONG_FTYPE_LONG_V2HI_V2HI, V_KMAXDS),
  DIRECT_DSP_BUILTIN (kmsda, kmsda, kmsda,
		      RISCV_LONG_FTYPE_LONG_ULONG_ULONG, KMSDA),
  DIRECT_DSP_BUILTIN (kmsda, kmsda, v_kmsda,
		      RISCV_LONG_FTYPE_LONG_V2HI_V2HI, V_KMSDA),
  DIRECT_DSP_BUILTIN (kmsxda, kmsxda, kmsxda,
		      RISCV_LONG_FTYPE_LONG_ULONG_ULONG, KMSXDA),
  DIRECT_DSP_BUILTIN (kmsxda, kmsxda, v_kmsxda,
		      RISCV_LONG_FTYPE_LONG_V2HI_V2HI, V_KMSXDA),
  /* DSP Extension: Signed 16bit Multiply with 64bit ADD/Subtract.  */
  DIRECT_DSP_BUILTIN (smal1, smal1, smal,
		      RISCV_LLONG_FTYPE_LLONG_LONG, SMAL),
  DIRECT_DSP_BUILTIN (smal1, smal1, v_smal,
		      RISCV_LLONG_FTYPE_LLONG_V2HI, V_SMAL),
  /* DSP Extension: 32bit MISC.  */
  DIRECT_DSP_BUILTIN (bitrev, bitrev, bitrev,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, BITREV),
  DIRECT_DSP_BUILTIN (wext, wext, wext,
		      RISCV_ULONG_FTYPE_LLONG_ULONG, WEXT),
  DIRECT_DSP_BUILTIN (bpick1, bpick1, bpick,
		      RISCV_ULONG_FTYPE_ULONG_ULONG_ULONG, BPICK),
  DIRECT_DSP_BUILTIN (insb, insb, insb,
		      RISCV_ULONG_FTYPE_ULONG_ULONG_ULONG, INSB),
  /* DSP Extension: 64bit Add and Subtract.  */
  DIRECT_DSP_BUILTIN (adddi3, adddi3, sadd64,
		      RISCV_LLONG_FTYPE_LLONG_LLONG, SADD64),
  DIRECT_DSP_BUILTIN (adddi3, adddi3, uadd64,
		      RISCV_LLONG_FTYPE_LLONG_LLONG, UADD64),
  DIRECT_DSP_BUILTIN (radddi3, radddi3, radd64,
		      RISCV_LLONG_FTYPE_LLONG_LLONG, RADD64),
  DIRECT_DSP_BUILTIN (uradddi3, uradddi3, uradd64,
		      RISCV_LLONG_FTYPE_LLONG_LLONG, URADD64),
  DIRECT_DSP_BUILTIN (dsp_kadddi3, dsp_kadddi3, kadd64,
		      RISCV_LLONG_FTYPE_LLONG_LLONG, KADD64),
  DIRECT_DSP_BUILTIN (dsp_ukadddi3, dsp_ukadddi3, ukadd64,
		      RISCV_LLONG_FTYPE_LLONG_LLONG, UKADD64),
  DIRECT_DSP_BUILTIN (subdi3, subdi3, ssub64,
		      RISCV_LLONG_FTYPE_LLONG_LLONG, SSUB64),
  DIRECT_DSP_BUILTIN (subdi3, subdi3, usub64,
		      RISCV_LLONG_FTYPE_LLONG_LLONG, USUB64),
  DIRECT_DSP_BUILTIN (rsubdi3, rsubdi3, rsub64,
		      RISCV_LLONG_FTYPE_LLONG_LLONG, RSUB64),
  DIRECT_DSP_BUILTIN (ursubdi3, ursubdi3, ursub64,
		      RISCV_LLONG_FTYPE_LLONG_LLONG, URSUB64),
  DIRECT_DSP_BUILTIN (dsp_ksubdi3, dsp_ksubdi3, ksub64,
		      RISCV_LLONG_FTYPE_LLONG_LLONG, KSUB64),
  DIRECT_DSP_BUILTIN (dsp_uksubdi3, dsp_uksubdi3, uksub64,
		      RISCV_LLONG_FTYPE_LLONG_LLONG, UKSUB64),
  /* DSP Extension: 32bit Multiply with 64bit Add/Subtract.  */
  DIRECT_DSP_BUILTIN (smar64_1, smar64_1, smar64,
		      RISCV_LLONG_FTYPE_LLONG_LONG_LONG, SMAR64),
  DIRECT_DSP_BUILTIN (smsr64, smsr64, smsr64,
		      RISCV_LLONG_FTYPE_LLONG_LONG_LONG, SMSR64),
  DIRECT_DSP_BUILTIN (umar64_1, umar64_1, umar64,
		      RISCV_LLONG_FTYPE_LLONG_ULONG_ULONG, UMAR64),
  DIRECT_DSP_BUILTIN (umsr64, umsr64, umsr64,
		      RISCV_LLONG_FTYPE_LLONG_ULONG_ULONG, UMSR64),
  DIRECT_DSP_BUILTIN (kmar64_1, kmar64_1, kmar64,
		      RISCV_LLONG_FTYPE_LLONG_LONG_LONG, KMAR64),
  DIRECT_DSP_BUILTIN (kmsr64, kmsr64, kmsr64,
		      RISCV_LLONG_FTYPE_LLONG_LONG_LONG, KMSR64),
  DIRECT_DSP_BUILTIN (ukmar64_1, ukmar64_1, ukmar64,
		      RISCV_LLONG_FTYPE_LLONG_ULONG_ULONG, UKMAR64),
  DIRECT_DSP_BUILTIN (ukmsr64, ukmsr64, ukmsr64,
		      RISCV_LLONG_FTYPE_LLONG_ULONG_ULONG, UKMSR64),
  /* DSP Extension: Signed 16bit Multiply with 64bit Add/Subtract.  */
  DIRECT_DSP_BUILTIN (smalbb, smalbb, smalbb,
		      RISCV_LLONG_FTYPE_LLONG_ULONG_ULONG, SMALBB),
  DIRECT_DSP_BUILTIN (smalbb, smalbb, v_smalbb,
		      RISCV_LLONG_FTYPE_LLONG_V2HI_V2HI, V_SMALBB),
  DIRECT_DSP_BUILTIN (smalbt, smalbt, smalbt,
		      RISCV_LLONG_FTYPE_LLONG_ULONG_ULONG, SMALBT),
  DIRECT_DSP_BUILTIN (smalbt, smalbt, v_smalbt,
		      RISCV_LLONG_FTYPE_LLONG_V2HI_V2HI, V_SMALBT),
  DIRECT_DSP_BUILTIN (smaltt, smaltt, smaltt,
		      RISCV_LLONG_FTYPE_LLONG_ULONG_ULONG, SMALTT),
  DIRECT_DSP_BUILTIN (smaltt, smaltt, v_smaltt,
		      RISCV_LLONG_FTYPE_LLONG_V2HI_V2HI, V_SMALTT),
  DIRECT_DSP_BUILTIN (smalda1, smalda1, smalda,
		      RISCV_LLONG_FTYPE_LLONG_ULONG_ULONG, SMALDA),
  DIRECT_DSP_BUILTIN (smalda1, smalda1, v_smalda,
		      RISCV_LLONG_FTYPE_LLONG_V2HI_V2HI, V_SMALDA),
  DIRECT_DSP_BUILTIN (smalxda1, smalxda1, smalxda,
		      RISCV_LLONG_FTYPE_LLONG_ULONG_ULONG, SMALXDA),
  DIRECT_DSP_BUILTIN (smalxda1, smalxda1, v_smalxda,
		      RISCV_LLONG_FTYPE_LLONG_V2HI_V2HI, V_SMALXDA),
  DIRECT_DSP_BUILTIN (smalds1, smalds1, smalds,
		      RISCV_LLONG_FTYPE_LLONG_ULONG_ULONG, SMALDS),
  DIRECT_DSP_BUILTIN (smalds1, smalds1, v_smalds,
		      RISCV_LLONG_FTYPE_LLONG_V2HI_V2HI, V_SMALDS),
  DIRECT_DSP_BUILTIN (smaldrs3, smaldrs3, smaldrs,
		      RISCV_LLONG_FTYPE_LLONG_ULONG_ULONG, SMALDRS),
  DIRECT_DSP_BUILTIN (smaldrs3, smaldrs3, v_smaldrs,
		      RISCV_LLONG_FTYPE_LLONG_V2HI_V2HI, V_SMALDRS),
  DIRECT_DSP_BUILTIN (smalxds1, smalxds1, smalxds,
		      RISCV_LLONG_FTYPE_LLONG_ULONG_ULONG, SMALXDS),
  DIRECT_DSP_BUILTIN (smalxds1, smalxds1, v_smalxds,
		      RISCV_LLONG_FTYPE_LLONG_V2HI_V2HI, V_SMALXDS),
  DIRECT_DSP_BUILTIN (smslda1, smslda1, smslda,
		      RISCV_LLONG_FTYPE_LLONG_ULONG_ULONG, SMSLDA),
  DIRECT_DSP_BUILTIN (smslda1, smslda1, v_smslda,
		      RISCV_LLONG_FTYPE_LLONG_V2HI_V2HI, V_SMSLDA),
  DIRECT_DSP_BUILTIN (smslxda1, smslxda1, smslxda,
		      RISCV_LLONG_FTYPE_LLONG_ULONG_ULONG, SMSLXDA),
  DIRECT_DSP_BUILTIN (smslxda1, smslxda1, v_smslxda,
		      RISCV_LLONG_FTYPE_LLONG_V2HI_V2HI, V_SMSLXDA),
  /* DSP Extension: augmented baseline.  */
  DIRECT_DSP_BUILTIN (uclip32, uclip32, uclip32,
		      RISCV_ULONG_FTYPE_LONG_ULONG, UCLIP32),
  DIRECT_DSP_BUILTIN (sclip32, sclip32, sclip32,
		      RISCV_LONG_FTYPE_LONG_ULONG, SCLIP32),
  DIRECT_DSP_BUILTIN (kabs, kabs, kabs,
		      RISCV_LONG_FTYPE_LONG, KABS),
  /* DSP Extension: Saturation.  */
  DIRECT_DSP_BUILTIN (kaddw, kaddw, kaddw,
		      RISCV_LONG_FTYPE_LONG_LONG, KADDW),
  DIRECT_DSP_BUILTIN (ksubw, ksubw, ksubw,
		      RISCV_LONG_FTYPE_LONG_LONG, KSUBW),
  DIRECT_DSP_BUILTIN (kaddh, kaddh, kaddh,
		      RISCV_LONG_FTYPE_LONG_LONG, KADDH),
  DIRECT_DSP_BUILTIN (ksubh, ksubh, ksubh,
		      RISCV_LONG_FTYPE_LONG_LONG, KSUBH),
  DIRECT_DSP_BUILTIN (ukaddw, ukaddw, ukaddw,
		      RISCV_LONG_FTYPE_LONG_LONG, UKADDW),
  DIRECT_DSP_BUILTIN (uksubw, uksubw, uksubw,
		      RISCV_LONG_FTYPE_LONG_LONG, UKSUBW),
  DIRECT_DSP_BUILTIN (ukaddh, ukaddh, ukaddh,
		      RISCV_LONG_FTYPE_LONG_LONG, UKADDH),
  DIRECT_DSP_BUILTIN (uksubh, uksubh, uksubh,
		      RISCV_LONG_FTYPE_LONG_LONG, UKSUBH),
  DIRECT_DSP_BUILTIN (kdmbb, kdmbb, kdmbb,
		      RISCV_LONG_FTYPE_ULONG_ULONG, KDMBB),
  DIRECT_DSP_BUILTIN (kdmbb, kdmbb, v_kdmbb,
		      RISCV_LONG_FTYPE_V2HI_V2HI, V_KDMBB),
  DIRECT_DSP_BUILTIN (kdmbt, kdmbt, kdmbt,
		      RISCV_LONG_FTYPE_ULONG_ULONG, KDMBT),
  DIRECT_DSP_BUILTIN (kdmbt, kdmbt, v_kdmbt,
		      RISCV_LONG_FTYPE_V2HI_V2HI, V_KDMBT),
  DIRECT_DSP_BUILTIN (kdmtt, kdmtt, kdmtt,
		      RISCV_LONG_FTYPE_ULONG_ULONG, KDMTT),
  DIRECT_DSP_BUILTIN (kdmtt, kdmtt, v_kdmtt,
		      RISCV_LONG_FTYPE_V2HI_V2HI, V_KDMTT),
  DIRECT_DSP_BUILTIN (khmbb, khmbb, khmbb,
		      RISCV_LONG_FTYPE_ULONG_ULONG, KHMBB),
  DIRECT_DSP_BUILTIN (khmbb, khmbb, v_khmbb,
		      RISCV_LONG_FTYPE_V2HI_V2HI, V_KHMBB),
  DIRECT_DSP_BUILTIN (khmbt, khmbt, khmbt,
		      RISCV_LONG_FTYPE_ULONG_ULONG, KHMBT),
  DIRECT_DSP_BUILTIN (khmbt, khmbt, v_khmbt,
		      RISCV_LONG_FTYPE_V2HI_V2HI, V_KHMBT),
  DIRECT_DSP_BUILTIN (khmtt, khmtt, khmtt,
		      RISCV_LONG_FTYPE_ULONG_ULONG, KHMTT),
  DIRECT_DSP_BUILTIN (khmtt, khmtt, v_khmtt,
		      RISCV_LONG_FTYPE_V2HI_V2HI, V_KHMTT),
  DIRECT_DSP_BUILTIN (kslraw, kslraw, kslraw,
		      RISCV_LONG_FTYPE_LONG_LONG, KSLRAW),
  DIRECT_DSP_BUILTIN (unspec_kslrawu, unspec_kslrawu, kslraw_u,
		      RISCV_LONG_FTYPE_LONG_LONG, KSLRAW_U),
  DIRECT_DSP_BUILTIN (smaxsi3, smaxsi3, max,
		      RISCV_LONG_FTYPE_LONG_LONG, MAX),
  DIRECT_DSP_BUILTIN (sminsi3, sminsi3, min,
		      RISCV_LONG_FTYPE_LONG_LONG, MIN),
  DIRECT_DSP_BUILTIN (unspec_ave, unspec_ave, ave,
		      RISCV_LONG_FTYPE_LONG_LONG, AVE),
  /* DSP Extension: 8bit Shift.  */
  DIRECT_DSP_BUILTIN (ashrv4qi3, ashrv8qi3, sra8,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, SRA8),
  DIRECT_DSP_BUILTIN (ashrv4qi3, ashrv4qi3, v_sra8,
		      RISCV_V4QI_FTYPE_V4QI_ULONG, V_SRA8),
  DIRECT_DSP_BUILTIN (ashrv8qi3, ashrv8qi3, v64_sra8,
		      RISCV_V8QI_FTYPE_V8QI_ULONG, V64_SRA8),
  DIRECT_DSP_BUILTIN (sra8_roundv4qi, sra8_roundv8qi, sra8_u,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, SRA8_U),
  DIRECT_DSP_BUILTIN (sra8_roundv4qi, sra8_roundv4qi, v_sra8_u,
		      RISCV_V4QI_FTYPE_V4QI_ULONG, V_SRA8_U),
  DIRECT_DSP_BUILTIN (sra8_roundv8qi, sra8_roundv8qi, v64_sra8_u,
		      RISCV_V8QI_FTYPE_V8QI_ULONG, V64_SRA8_U),
  DIRECT_DSP_BUILTIN (lshrv4qi3, lshrv8qi3, srl8,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, SRL8),
  DIRECT_DSP_BUILTIN (lshrv4qi3, lshrv4qi3, v_srl8,
		      RISCV_UV4QI_FTYPE_UV4QI_ULONG, V_SRL8),
  DIRECT_DSP_BUILTIN (lshrv8qi3, lshrv8qi3, v64_srl8,
		      RISCV_UV8QI_FTYPE_UV8QI_ULONG, V64_SRL8),
  DIRECT_DSP_BUILTIN (srl8_roundv4qi, srl8_roundv8qi, srl8_u,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, SRL8_U),
  DIRECT_DSP_BUILTIN (srl8_roundv4qi, srl8_roundv4qi, v_srl8_u,
		      RISCV_UV4QI_FTYPE_UV4QI_ULONG, V_SRL8_U),
  DIRECT_DSP_BUILTIN (srl8_roundv8qi, srl8_roundv8qi, v64_srl8_u,
		      RISCV_UV8QI_FTYPE_UV8QI_ULONG, V64_SRL8_U),
  DIRECT_DSP_BUILTIN (ashlv4qi3, ashlv8qi3, sll8,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, SLL8),
  DIRECT_DSP_BUILTIN (ashlv4qi3, ashlv4qi3, v_sll8,
		      RISCV_UV4QI_FTYPE_UV4QI_ULONG, V_SLL8),
  DIRECT_DSP_BUILTIN (ashlv8qi3, ashlv8qi3, v64_sll8,
		      RISCV_UV8QI_FTYPE_UV8QI_ULONG, V64_SLL8),
  DIRECT_DSP_BUILTIN (kslli8v4qi, kslli8v8qi, ksll8,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, KSLL8),
  DIRECT_DSP_BUILTIN (kslli8v4qi, kslli8v4qi, v_ksll8,
		      RISCV_V4QI_FTYPE_V4QI_ULONG, V_KSLL8),
  DIRECT_DSP_BUILTIN (kslli8v8qi, kslli8v8qi, v64_ksll8,
		      RISCV_V8QI_FTYPE_V8QI_ULONG, V64_KSLL8),
  DIRECT_DSP_BUILTIN (kslrav4qi, kslrav8qi, kslra8,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, KSLRA8),
  DIRECT_DSP_BUILTIN (kslrav4qi, kslrav4qi, v_kslra8,
		      RISCV_V4QI_FTYPE_V4QI_ULONG, V_KSLRA8),
  DIRECT_DSP_BUILTIN (kslrav8qi, kslrav8qi, v64_kslra8,
		      RISCV_V8QI_FTYPE_V8QI_ULONG, V64_KSLRA8),
  DIRECT_DSP_BUILTIN (kslrav4qi_round, kslrav8qi_round, kslra8_u,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, KSLRA8_U),
  DIRECT_DSP_BUILTIN (kslrav4qi_round, kslrav4qi_round, v_kslra8_u,
		      RISCV_V4QI_FTYPE_V4QI_ULONG, V_KSLRA8_U),
  DIRECT_DSP_BUILTIN (kslrav8qi_round, kslrav8qi_round, v64_kslra8_u,
		      RISCV_V8QI_FTYPE_V8QI_ULONG, V64_KSLRA8_U),
  DIRECT_DSP_BUILTIN (clo, clo, clo,
		      RISCV_ULONG_FTYPE_ULONG, CLO),
  DIRECT_DSP_BUILTIN (clzsi2, clzsi2, clz,
		      RISCV_ULONG_FTYPE_ULONG, CLZ),
  DIRECT_DSP_BUILTIN (pbsad, pbsad, pbsad,
		      RISCV_ULONG_FTYPE_ULONG_ULONG, PBSAD),
  DIRECT_DSP_BUILTIN (pbsada, pbsada, pbsada,
		      RISCV_ULONG_FTYPE_ULONG_ULONG_ULONG, PBSADA),
  DIRECT_DSP_BUILTIN (unspec_bswap16, unspec_bswap16, swap16,
		      RISCV_ULONG_FTYPE_ULONG, SWAP16),
  DIRECT_DSP_BUILTIN (unspec_bswap16, unspec_bswap16, v_swap16,
		      RISCV_V2HI_FTYPE_V2HI, V_SWAP16),
  DIRECT_DSP_BUILTIN (unspec_bswap8, unspec_bswap8, swap8,
		      RISCV_ULONG_FTYPE_ULONG, SWAP8),
  DIRECT_DSP_BUILTIN (unspec_bswap8, unspec_bswap8, v_swap8,
		      RISCV_V4QI_FTYPE_V4QI, V_SWAP8),
  DIRECT_DSP_BUILTIN (sclip8v4qi, sclip8v8qi, sclip8,
		      RISCV_LONG_FTYPE_LONG_USI, SCLIP8),
  DIRECT_DSP_BUILTIN (sclip8v4qi, sclip8v4qi, v_sclip8,
		      RISCV_V4QI_FTYPE_V4QI_USI, V_SCLIP8),
  DIRECT_DSP_BUILTIN (sclip8v8qi, sclip8v8qi, v64_sclip8,
		      RISCV_V8QI_FTYPE_V8QI_USI, V64_SCLIP8),
  DIRECT_DSP_BUILTIN (uclip8v4qi, uclip8v8qi, uclip8,
		      RISCV_ULONG_FTYPE_ULONG_USI, UCLIP8),
  DIRECT_DSP_BUILTIN (uclip8v4qi, uclip8v4qi, v_uclip8,
		      RISCV_UV4QI_FTYPE_UV4QI_USI, V_UCLIP8),
  DIRECT_DSP_BUILTIN (uclip8v8qi, uclip8v8qi, v64_uclip8,
		      RISCV_UV8QI_FTYPE_UV8QI_USI, V64_UCLIP8),
  /* String */
  DIRECT_DSP_BUILTIN (ffb, ffb, ffb,
		      RISCV_LONG_FTYPE_ULONG_ULONG, FFB),
  DIRECT_DSP_BUILTIN (ffmism, ffmism, ffmism,
		      RISCV_LONG_FTYPE_ULONG_ULONG, FFMISM),
  DIRECT_DSP_BUILTIN (flmism, flmism, flmism,
		      RISCV_LONG_FTYPE_ULONG_ULONG, FLMISM)
};

/* Index I is the function declaration for riscv_builtins[I], or null if the
   function isn't defined on this target.  */
static GTY(()) tree riscv_builtin_decls[ARRAY_SIZE (riscv_builtins)];

/* Get the index I of the function declaration for riscv_builtin_decls[I]
   using the instruction code or return null if not defined for the target.  */
static GTY(()) int riscv_builtin_decl_index[NUM_INSN_CODES];

#define GET_BUILTIN_DECL(CODE) \
  riscv_builtin_decls[riscv_builtin_decl_index[(CODE)]]

/* Return the function type associated with function prototype TYPE.  */

static tree
riscv_build_function_type (enum riscv_function_type type)
{
  static tree types[(int) RISCV_MAX_FTYPE_MAX];

  if (types[(int) type] == NULL_TREE)
    switch (type)
      {
#define DEF_RISCV_FTYPE(NUM, ARGS)					\
  case RISCV_FTYPE_NAME##NUM ARGS:					\
    types[(int) type]							\
      = build_function_type_list (RISCV_FTYPE_ATYPES##NUM ARGS,		\
				  NULL_TREE);				\
    break;
#include "config/riscv/riscv-ftypes.def"
#undef DEF_RISCV_FTYPE
      default:
	gcc_unreachable ();
      }

  return types[(int) type];
}

/* Implement TARGET_INIT_BUILTINS.  */

tree riscv_fp16_type_node = NULL_TREE;

static void
riscv_init_fp16_types (void)
{
  riscv_fp16_type_node = make_node (REAL_TYPE);
  TYPE_PRECISION (riscv_fp16_type_node) = 16;
  layout_type (riscv_fp16_type_node);

  (*lang_hooks.types.register_builtin_type) (riscv_fp16_type_node, "__fp16");
}

void
riscv_init_builtins (void)
{
  if (TARGET_FP16)
    riscv_init_fp16_types ();

  for (size_t i = 0; i < ARRAY_SIZE (riscv_builtins); i++)
    {
      const struct riscv_builtin_description *d = &riscv_builtins[i];
      tree type = riscv_build_function_type (d->prototype);
      riscv_builtin_decls[i]
	= add_builtin_function (d->name, type, i, BUILT_IN_MD, NULL, NULL);
      riscv_builtin_decl_index[d->icode] = i;
    }
}

/* Implement TARGET_BUILTIN_DECL.  */

tree
riscv_builtin_decl (unsigned int code, bool initialize_p ATTRIBUTE_UNUSED)
{
  if (code >= ARRAY_SIZE (riscv_builtins))
    return error_mark_node;
  return riscv_builtin_decls[code];
}

/* Take argument ARGNO from EXP's argument list and convert it into
   an expand operand.  Store the operand in *OP.  */

static void
riscv_prepare_builtin_arg (struct expand_operand *op, tree exp, unsigned argno,
			   enum insn_code icode, bool has_target_p)
{
  enum machine_mode mode = insn_data[icode].operand[argno + has_target_p].mode;
  rtx arg = expand_normal (CALL_EXPR_ARG (exp, argno));
  rtx tmp_rtx = gen_reg_rtx (mode);

  if (!(*insn_data[icode].operand[argno + has_target_p].predicate) (arg, mode))
    {
      if (GET_MODE_SIZE (mode) < GET_MODE_SIZE (GET_MODE (arg)))
	{
	  tmp_rtx = simplify_gen_subreg (mode, arg, GET_MODE (arg), 0);
	  arg = tmp_rtx;
	}
      else if (VECTOR_MODE_P (mode) && CONST_INT_P (arg))
	{
	  /* Handle CONST_INT covert to CONST_VECTOR.  */
	  int nunits = GET_MODE_NUNITS (mode);
	  int i, shift = 0;
	  rtvec v = rtvec_alloc (nunits);
	  int val = INTVAL (arg);
	  enum machine_mode val_mode = (mode == V4QImode) ? QImode : HImode;
	  int shift_acc = (val_mode == QImode) ? 8 : 16;
	  int mask = (val_mode == QImode) ? 0xff : 0xffff;
	  int tmp_val = val;

	  for (i = 0; i < nunits; i++)
	    {
	      tmp_val = (val >> shift) & mask;
	      RTVEC_ELT (v, i) = gen_int_mode (tmp_val, val_mode);
	      shift += shift_acc;
	    }

	  arg = copy_to_mode_reg (mode, gen_rtx_CONST_VECTOR (mode, v));
	}
      else
	{
	  convert_move (tmp_rtx, arg, false);
	  arg = tmp_rtx;
	}
    }

  create_input_operand (op, arg, mode);
}

/* Expand instruction ICODE as part of a built-in function sequence.
   Use the first NOPS elements of OPS as the instruction's operands.
   HAS_TARGET_P is true if operand 0 is a target; it is false if the
   instruction has no target.

   Return the target rtx if HAS_TARGET_P, otherwise return const0_rtx.  */

static rtx
riscv_expand_builtin_insn (enum insn_code icode, unsigned int n_ops,
			   struct expand_operand *ops, bool has_target_p)
{
  if (!maybe_expand_insn (icode, n_ops, ops))
    {
      error ("invalid argument to built-in function");
      return has_target_p ? gen_reg_rtx (ops[0].mode) : const0_rtx;
    }

  return has_target_p ? ops[0].value : const0_rtx;
}

/* Expand a RISCV_BUILTIN_DIRECT or RISCV_BUILTIN_DIRECT_NO_TARGET function;
   HAS_TARGET_P says which.  EXP is the CALL_EXPR that calls the function
   and ICODE is the code of the associated .md pattern.  TARGET, if nonnull,
   suggests a good place to put the result.  */

static rtx
riscv_expand_builtin_direct (enum insn_code icode, rtx target, tree exp,
			     bool has_target_p)
{
  struct expand_operand ops[MAX_RECOG_OPERANDS];

  /* Map any target to operand 0.  */
  int opno = 0;
  enum machine_mode mode = insn_data[icode].operand[opno].mode;

  if (has_target_p)
    {
      if (! target
	  || GET_MODE (target) != mode
	  || ! (*insn_data[icode].operand[opno].predicate) (target, mode))
	target = gen_reg_rtx (mode);

      create_output_operand (&ops[opno++], target, mode);
    }

  /* Map the arguments to the other operands.  */
  gcc_assert (opno + call_expr_nargs (exp)
	      == insn_data[icode].n_generator_args);

  for (int argno = 0; argno < call_expr_nargs (exp); argno++)
    riscv_prepare_builtin_arg (&ops[opno++], exp, argno, icode, has_target_p);

  return riscv_expand_builtin_insn (icode, opno, ops, has_target_p);
}

/* Expand a RISCV_BUILTIN_ECALL function, the ecall return value
   store in A0 register, the first pass argument save in A7/T0 register,
   and other pass argument store in A0 to A6 register.  */
static rtx
riscv_expand_builtin_ecall (enum insn_code icode, tree exp)
{
  struct expand_operand ops[MAX_RECOG_OPERANDS];
  rtx reg_arg0 = TARGET_RVE ? gen_rtx_REG (Pmode, T0_REGNUM)
			     : gen_rtx_REG (Pmode, A7_REGNUM);
  rtx retval = gen_rtx_REG (Pmode, A0_REGNUM);
  /* Map any target to operand 0.  */
  int opno = 0;

  /* Store return value in A0 register.  */
  create_output_operand (&ops[opno++], retval, TYPE_MODE (TREE_TYPE (exp)));

  /* Map the arguments to the other operands.  */
  gcc_assert (opno + call_expr_nargs (exp)
	      == insn_data[icode].n_generator_args);

  /* Process first argument save in T0/A7 register.  */
  emit_move_insn (reg_arg0, expand_normal (CALL_EXPR_ARG (exp, 0)));
  create_input_operand (&ops[opno++], reg_arg0,
			TYPE_MODE (TREE_TYPE (CALL_EXPR_ARG (exp, 0))));

  /* Process other arguments.  */
  for (int argno = 1; argno < call_expr_nargs (exp); argno++)
    {
      rtx reg_argno = gen_rtx_REG (Pmode, S1_REGNUM + argno);
      tree arg = CALL_EXPR_ARG (exp, argno);
      emit_move_insn (reg_argno, expand_normal (arg));
      create_input_operand (&ops[opno++], reg_argno,
			    TYPE_MODE (TREE_TYPE (arg)));
    }

  if (!maybe_expand_insn (icode, opno, ops))
    error ("invalid argument to built-in function");

  return retval;
}

/* Expand a RISCV_BUILTIN_ECALL function, the ebreak instruction
   pass argument save in A7/T0 register.  */
static rtx
riscv_expand_builtin_ebreak (enum insn_code icode, tree exp)
{
  struct expand_operand ops[MAX_RECOG_OPERANDS];
  rtx reg_arg0 = TARGET_RVE ? gen_rtx_REG (Pmode, T0_REGNUM)
			     : gen_rtx_REG (Pmode, A7_REGNUM);
  int opno = 0;

  /* Process first argument save in T0/A7 register.  */
  emit_move_insn (reg_arg0, expand_normal (CALL_EXPR_ARG (exp, 0)));
  create_input_operand (&ops[opno++], reg_arg0,
			TYPE_MODE (TREE_TYPE (CALL_EXPR_ARG (exp, 0))));

  if (!maybe_expand_insn (icode, opno, ops))
    error ("invalid argument to built-in function");

  return const0_rtx;
}

/* Implement TARGET_EXPAND_BUILTIN.  */

rtx
riscv_expand_builtin (tree exp, rtx target, rtx subtarget ATTRIBUTE_UNUSED,
		      machine_mode mode ATTRIBUTE_UNUSED,
		      int ignore ATTRIBUTE_UNUSED)
{
  tree fndecl = TREE_OPERAND (CALL_EXPR_FN (exp), 0);
  unsigned int fcode = DECL_MD_FUNCTION_CODE (fndecl);
  const struct riscv_builtin_description *d = &riscv_builtins[fcode];
  enum insn_code icode = TARGET_64BIT ? d->icode64 : d->icode;

  if (!TARGET_DSP
      && d->fcode > RISCV_BUILTIN_DSP_BEGIN
      && d->fcode < RISCV_BUILTIN_DSP_END)
    error ("don't support DSP extension instructions");

  switch (d->fcode)
    {
    case RISCV_BUILTIN_FRFLAGS_FENV:
    case RISCV_BUILTIN_FSFLAGS_FENV:
    case RISCV_BUILTIN_FRCSR:
    case RISCV_BUILTIN_FSCSR:
    case RISCV_BUILTIN_FWCSR:
    case RISCV_BUILTIN_FRRM:
    case RISCV_BUILTIN_FSRM:
    case RISCV_BUILTIN_FWRM:
    case RISCV_BUILTIN_FRFLAGS:
    case RISCV_BUILTIN_FSFLAGS:
    case RISCV_BUILTIN_FWFLAGS:
      if (!TARGET_HARD_FLOAT)
	{
	  error ("this builtin function is only available "
                 "on enable Floating-Point Instruction Extension.");
          return NULL_RTX;
	}
      break;

    case RISCV_BUILTIN_AMOW:
      if (!TARGET_ATOMIC)
	{
	  error ("this builtin function is only available "
                 "on enable Atomic Instruction Extension. try -matomic");
          return NULL_RTX;
	}
      break;

    case RISCV_BUILTIN_AMOD:
      if (!(TARGET_64BIT && TARGET_ATOMIC))
	{
	  error ("this builtin function is only available "
                 "on enable 64-bit Atomic Instruction Extension. try -matomic");
          return NULL_RTX;
	}
      break;

    case RISCV_BUILTIN_LRD:
    case RISCV_BUILTIN_SCD:
      if (!TARGET_64BIT)
	{
	  error ("this builtin function is only available "
                 "on the 64-bit toolchain");
          return NULL_RTX;
	}
      break;

    case RISCV_BUILTIN_CSRRW:
    case RISCV_BUILTIN_CSRRS:
    case RISCV_BUILTIN_CSRRC:
    case RISCV_BUILTIN_CSRW:
    case RISCV_BUILTIN_CSRS:
    case RISCV_BUILTIN_CSRC:
      if (!CONST_INT_P (expand_normal (CALL_EXPR_ARG (exp, 1))))
	{
	  if (optimize == 0)
	    error ("Invalid argument to built-in function, "
		   "the second argument must be constant value, if that is"
		   "constant value try to compile with higher optimization"
		   " level (e.g. -O1).");
	  else
	    error ("Invalid argument to built-in function, "
		   "the second argument must be constant value.");
	  return NULL_RTX;
	}
      break;

    default:
      break;
    }

  switch (d->fcode)
    {
    case RISCV_BUILTIN_ECALL:
      return riscv_expand_builtin_ecall (icode, exp);
    case RISCV_BUILTIN_FENCEI:
      emit_insn (gen_riscv_fencei ());
      return target;
    case RISCV_BUILTIN_EBREAK:
      return riscv_expand_builtin_ebreak (icode, exp);

    default:
      break;
    }

  switch (d->builtin_type)
    {
    case RISCV_BUILTIN_DIRECT:
      return riscv_expand_builtin_direct (icode, target, exp, true);

    case RISCV_BUILTIN_DIRECT_NO_TARGET:
      return riscv_expand_builtin_direct (icode, target, exp, false);

    default:
      break;
    }

  gcc_unreachable ();
}

/* Implement TARGET_ATOMIC_ASSIGN_EXPAND_FENV.  */

void
riscv_atomic_assign_expand_fenv (tree *hold, tree *clear, tree *update)
{
  if (!TARGET_HARD_FLOAT)
    return;

  tree frflags = GET_BUILTIN_DECL (CODE_FOR_riscv_frflags);
  tree fsflags = GET_BUILTIN_DECL (CODE_FOR_riscv_fsflags);
  tree old_flags = create_tmp_var_raw (RISCV_ATYPE_USI);

  *hold = build4 (TARGET_EXPR, RISCV_ATYPE_USI, old_flags,
		  build_call_expr (frflags, 0), NULL_TREE, NULL_TREE);
  *clear = build_call_expr (fsflags, 1, old_flags);
  *update = NULL_TREE;
}
